Repository mongodb/node-mongodb-native, pull requests merged in 2021-12, with the labels that each got.

#3048 docs(NODE-3753): Update testing readme file
  CONTRIBUTING.md
  test/readme.md
Labels: Team Review

#3045 fix(NODE-3711): retry txn end on retryable write
  src/error.ts
  src/sessions.ts
  test/functional/transactions.test.js
  test/unit/error.test.js
Labels: Team Review

#3047 fix(NODE-3711): retry txn end on retryable write
  lib/core/error.js
  lib/core/sessions.js
  test/functional/transactions.test.js
  test/unit/error.test.js
Labels: Team Review

#3060 fix(NODE-3705): ReadPreference.fromOptions omitting hedge and maxStalenessSeconds when readPreference is a string
  CONTRIBUTORS.md
  src/read_preference.ts
  test/functional/readpreference.test.js
  test/unit/read_preference.test.ts
Labels: Team Review

#3064 refactor(NODE-3717): reorganize tests part 2
  .evergreen/run-serverless-tests.sh
  test/integration/crud/bulk.test.js
  test/integration/crud/crud.prose.test.js
  test/integration/crud/crud.spec.test.js
  test/integration/crud/crud_api.test.js
  test/integration/load-balancers/load_balancers.spec.test.js
  test/integration/max-staleness/max_staleness.test.js
  test/integration/retryable-reads/retryable_reads.spec.test.js
  test/integration/retryable-writes/retryable_writes.spec.test.js
  test/integration/versioned-api/versioned_api.spec.test.js
Labels: Team Review

#3052 docs: Clarify that deprecation is a "feat" type commit
  CONTRIBUTING.md
Labels: Primary Review

#3065 test(NODE-3801): fix explain tests to work with latest server
  test/functional/explain.test.js
Labels: Team Review

#3063 refactor(NODE-3788): update names of offensive error codes
  src/error.ts
  test/unit/error.test.js
Labels: Team Review

#3068 docs: Fix a typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Team Review

#3066 refactor(NODE-3789):Update tests with oppressive language in their description
  test/functional/connections_stepdown.test.js
Labels: Team Review

#3040 fix(NODE-3765): make replacement for replaceOne operations without _id
  src/bulk/common.ts
  src/collection.ts
  test/types/community/collection/bulkWrite.test-d.ts
  test/types/community/collection/replaceX.test-d.ts
Labels: tracked-in-jira, Team Review, External Submission

#3061 feat(NODE-3784): Add `enableUtf8Validation` option
  src/bson.ts
  src/cmap/commands.ts
  src/cmap/connection.ts
  src/cmap/wire_protocol/shared.ts
  src/connection_string.ts
  src/db.ts
  src/operations/create_collection.ts
  src/operations/map_reduce.ts
  test/functional/cmap/commands.test.ts
  test/types/bson.test-d.ts
  test/unit/commands.test.ts
Labels: Team Review

#3076 chore: fix invalid use of typeof operator
  .eslintrc.json
  src/cmap/stream_description.ts
Labels: Team Review

#3078 fix: stricter protocol check in connection string
  package-lock.json
  package.json
Labels: Team Review

#3074 feat(NODE-3784): Add `enableUtf8Validation` option
  src/bson.ts
  src/cmap/commands.ts
  src/cmap/connection.ts
  src/cmap/wire_protocol/shared.ts
  src/connection_string.ts
  src/db.ts
  src/operations/create_collection.ts
  src/operations/map_reduce.ts
  test/functional/cmap/commands.test.ts
  test/types/bson.test-d.ts
  test/unit/commands.test.ts
Labels: Team Review

#3079 fix(NODE-3675): SRV option bug correctly defaults authSource to $external
  src/cmap/auth/mongo_credentials.ts
  src/cmap/auth/providers.ts
  src/connection_string.ts
  test/unit/connection_string.test.ts
Labels: Team Review

#3083 refactor(NODE-3717): test reorg part 3 - sessions and transactions
  .evergreen/run-serverless-tests.sh
  test/integration/sessions/sessions.spec.test.js
  test/integration/sessions/sessions.test.js
  test/integration/transactions/transactions.spec.test.js
  test/integration/transactions/transactions.test.js
Labels: Team Review

#3084 docs: Fix a typo in FindOptions doc
  src/operations/find.ts
Labels: Team Review, External Submission

#3077 fix(NODE-3803): Fix _id typing on collection create operations
  src/collection.ts
  src/index.ts
  src/mongo_types.ts
  test/types/basic_schema.test-d.ts
  test/types/community/collection/filterQuery.test-d.ts
  test/types/community/collection/insertX.test-d.ts
  test/types/schema_helpers.test-d.ts
  test/types/union_schema.test-d.ts
Labels: Team Review

#3071 refactor(NODE-3790): Remove oppressive language from test files
  src/constants.ts
  src/utils.ts
  test/benchmarks/driverBench/index.js
  test/functional/causal_consistency.test.js
  test/functional/change_stream.test.js
  test/functional/change_stream_spec.test.js
  test/functional/cmap/connection.test.js
  test/functional/collations.test.js
  test/functional/collection.test.js
  test/functional/command_monitoring.test.js
  test/functional/command_write_concern.test.js
  test/functional/core/shared.js
  test/functional/mongo_client_options.test.js
  test/functional/promises_db.test.js
  test/functional/replicaset_mock.test.js
  test/functional/scram_sha_256.test.js
  test/functional/shared.js
  test/functional/spec-runner/index.js
  test/functional/unit-sdam/monitoring.test.js
  test/functional/unit-sdam/server_selection/spec.test.js
  test/functional/unit-sdam/spec.test.js
  test/functional/unit-sdam/srv_polling.test.js
  test/functional/unit-sdam/topology.test.js
  test/functional/unit-sessions/client.test.js
  test/functional/unit-sessions/collection.test.js
  test/functional/unit_bypass_validation.test.js
  test/functional/unit_create_index_error.test.js
  test/functional/view.test.js
  test/functional/write_concern.test.js
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
  test/integration/max-staleness/max_staleness.test.js
  test/integration/sessions/sessions.test.js
  test/integration/shared.js
  test/manual/atlas_connectivity.test.js
  test/manual/ocsp_support.test.js
  test/manual/tls_support.test.js
  test/tools/common.js
  test/tools/mongodb-mock/index.js
  test/tools/spec-runner/index.js
  test/unit/_MISC_optional_require.test.js
  test/unit/_MISC_scram_iterations.test.js
  test/unit/cmap/connect.test.js
  test/unit/cmap/connection.test.js
  test/unit/cmap/connection_pool.test.js
  test/unit/cmap/message_stream.test.js
  test/unit/cursor/find_cursor.test.js
  test/unit/error.test.js
  test/unit/polling_srv_records_for_mongos_discovery.prose.test.ts
  test/unit/sessions.test.js
  test/unit/unit_bulk_write.test.js
  test/unit/unit_client.test.js
  test/unit/unit_snappy.test.js
  test/unit/unit_wire_version.test.js
  test/unit/utils.test.js
Labels: Team Review

#3086 refactor(NODE-3717): test reorg part 4
  test/integration/causal-consistency/causal_consistency.test.js
  test/integration/change-streams/change_stream.test.js
  test/integration/change-streams/change_streams.spec.test.js
  test/integration/collection-management/collection_management.spec.test.js
  test/integration/command-monitoring/command_monitoring.spec.test.js
  test/integration/command-monitoring/command_monitoring.test.js
  test/integration/connection-monitoring-and-pooling/connection.test.js
  test/integration/read-write-concern/read_write_concern.spec.test.js
  test/integration/read-write-concern/write_concern.test.js
  test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.spec.test.js
  test/integration/unified-test-format/unified_test_format.spec.test.ts
  test/integration/uri-options/uri.test.js
  test/integration/uri-options/uri_options.spec.test.js
  test/unit/cmap/connection_monitoring_and_pooling.spec.test.js
  test/unit/cmap/connection_pool.test.js
  test/unit/connection_string.spec.test.ts
  test/unit/connection_string.test.ts
Labels: Team Review

#3082 feat(NODE-3793): Remove offensive language from code and tests
  src/cmap/commands.ts
  src/cmap/connection.ts
  src/collection.ts
  src/db.ts
  src/read_preference.ts
  test/functional/cursor.test.js
  test/unit/db.test.ts
  test/unit/read_preference.test.ts
Labels: Team Review

#2972 feat(NODE-3589): support dot-notation attributes in Filter
  .evergreen/run-checks.sh
  README.md
  src/index.ts
  src/mongo_types.ts
  test/types/community/collection/filterQuery.test-d.ts
Labels: tracked-in-jira, Team Review, External Submission

#3041 feat(NODE-3633): add Socks5 support
  .evergreen/config.yml
  .evergreen/config.yml.in
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-custom-csfle-tests.sh
  .evergreen/run-socks5-tests.sh
  package-lock.json
  package.json
  src/cmap/connect.ts
  src/cmap/connection.ts
  src/connection_string.ts
  src/deps.ts
  src/encrypter.ts
  src/index.ts
  src/mongo_client.ts
  src/utils.ts
  test/manual/socks5.test.ts
  test/spec/uri-options/proxy-options.json
  test/spec/uri-options/proxy-options.yml
  test/tools/runner/config.js
Labels: Team Review

#3087 refactor(NODE-3717): reorganize tests pt5
  test/functional/byo_promises.test.js
  test/functional/collations.test.js
  test/functional/cursor_async_iterator.test.js
  test/integration/bson-decimal128/decimal128.test.js
  test/integration/collation/collations.test.js
  test/integration/collection-management/collection.test.js
  test/integration/crud/find.test.js
  test/integration/crud/find_and_modify.test.js
  test/integration/crud/remove.test.js
  test/integration/index_management.test.js
  test/integration/read-write-concern/readconcern.test.js
  test/tools/contexts/index.js
  test/tools/contexts/other.js
  test/tools/contexts/shared.js
  test/unit/_MISC_collations.test.js
  test/unit/_MISC_write_concern.test.js
Labels: Team Review
