Repository mongodb/node-mongodb-native, pull requests merged in 2021-11, with the labels that each got.

#3022 feat(NODE-3083): support aggregate writes on secondaries
  src/cmap/connection.ts
  src/operations/aggregate.ts
  src/operations/command.ts
  src/operations/execute_operation.ts
  src/operations/operation.ts
  src/sdam/server.ts
  src/sdam/server_selection.ts
  src/sdam/topology.ts
  test/functional/crud_spec.test.js
  test/spec/crud/unified/aggregate-write-readPreference.json
  test/spec/crud/unified/aggregate-write-readPreference.yml
  test/spec/crud/unified/db-aggregate-write-readPreference.json
  test/spec/crud/unified/db-aggregate-write-readPreference.yml
  test/unit/operations/aggregate.test.js
  test/unit/sdam/server_selection.test.js
Labels: Team Review

#3006 fix(NODE-3116): reschedule unreliable async interval first
  src/utils.ts
  test/unit/utils.test.js
Labels: Team Review

#3021 feat(NODE-3728): Allow to pass `authorizedCollections` option to the `db.listCollections` method
  src/operations/list_collections.ts
  test/unit/operations/list_collections.test.js
Labels: tracked-in-jira, Team Review

#3032 fix(NODE-3344): allow setting `defaultTransactionOptions` with POJO rather than ReadConcern instance
  src/transactions.ts
  test/types/sessions.test-d.ts
Labels: Team Review

#3034 feat(NODE-3692): make change stream events typing more generic
  src/change_stream.ts
  test/types/mongodb.test-d.ts
Labels: Team Review

#3036 feat(NODE-3446): deprecate mapReduce command
  src/collection.ts
  test/types/mongodb.test-d.ts
Labels: Team Review

#3033 refactor(NODE-3273): remove undefined error param from topology open event
  src/sdam/topology.ts
  test/functional/connection.test.js
Labels: Team Review

#3031 feat(NODE-3467): implement srvMaxHosts, srvServiceName options
  .mocharc.json
  package-lock.json
  package.json
  src/connection_string.ts
  src/mongo_client.ts
  src/sdam/srv_polling.ts
  src/sdam/topology.ts
  src/sdam/topology_description.ts
  src/utils.ts
  test/functional/connection_leak_detector.js
  test/functional/uri_options_spec.test.js
  test/integration/initial-dns-seedlist-discovery/initial_dns_seedlist_discovery.spec.test.ts
  test/tools/mock.js
  test/tools/utils.js
  test/unit/connection_string.test.js
  test/unit/mongo_client.test.js
  test/unit/polling_srv_records_for_mongos_discovery.prose.test.ts
  test/unit/utils.test.js
Labels: Team Review

#3039 feat(NODE-3729): add withId to default return type for collection.find and collection.findOne
  src/collection.ts
  test/types/community/collection/filterQuery.test-d.ts
  test/types/community/collection/findX.test-d.ts
  test/types/mongodb.test-d.ts
  test/types/union_schema.test-d.ts
Labels: tracked-in-jira, Team Review, External Submission

#3059 test(NODE-3778): sync ADL spec test files
  test/spec/atlas-data-lake-testing/estimatedDocumentCount.json
  test/spec/atlas-data-lake-testing/estimatedDocumentCount.yml
Labels: Team Review

#3055 fix(NODE-3767): don't delete dbName if authSource is provided
  src/connection_string.ts
  test/unit/connection_string.test.js
  test/unit/mongo_client.test.js
Labels: Team Review, External Submission

#3057 test(NODE-3763): expand tls/ssl options parsing tests
  test/unit/connection_string.test.js
Labels: Team Review

#3058 fix(NODE-2370): correct a return type of hasNext()
  src/change_stream.ts
Labels: Team Review, External Submission

#3053 fix(NODE-3770): Filter type uses WithId on the schema
  src/collection.ts
  src/mongo_types.ts
  test/types/community/collection/findX.test-d.ts
  test/types/schema_helpers.test-d.ts
  test/types/union_schema.test-d.ts
Labels: Team Review

#3054 fix(NODE-3627): Enable flexible BSON validation for server error key containing invalid utf-8
  package-lock.json
  package.json
  src/bson.ts
  src/cmap/commands.ts
  test/unit/commands.test.ts
Labels: Team Review
