Repository mongodb/node-mongodb-native, pull requests merged in 2022-04, with the labels that each got.

#3167 feat(NODE-3699): add support for `comment` field
  src/change_stream.ts
  src/cmap/connection.ts
  src/cursor/abstract_cursor.ts
  src/operations/aggregate.ts
  src/operations/command.ts
  src/operations/delete.ts
  src/operations/find.ts
  src/operations/find_and_modify.ts
  src/operations/get_more.ts
  src/operations/indexes.ts
  src/operations/insert.ts
  src/operations/list_collections.ts
  src/operations/list_databases.ts
  src/operations/update.ts
  test/integration/enumerate_collections.test.ts
  test/integration/enumerate_databases.prose.test.ts
  test/integration/enumerate_databases.test.ts
  test/integration/enumerate_indexes.test.ts
  test/integration/node-specific/comment_with_falsy_values.test.ts
  test/integration/unified-test-format/unified_test_format.spec.test.ts
  test/spec/change-streams/unified/change-streams.json
  test/spec/change-streams/unified/change-streams.yml
  test/spec/crud/unified/aggregate.json
  test/spec/crud/unified/aggregate.yml
  test/spec/crud/unified/bulkWrite-comment.json
  test/spec/crud/unified/bulkWrite-comment.yml
  test/spec/crud/unified/deleteMany-comment.json
  test/spec/crud/unified/deleteMany-comment.yml
  test/spec/crud/unified/deleteOne-comment.json
  test/spec/crud/unified/deleteOne-comment.yml
  test/spec/crud/unified/find-comment.json
  test/spec/crud/unified/find-comment.yml
  test/spec/crud/unified/findOneAndDelete-comment.json
  test/spec/crud/unified/findOneAndDelete-comment.yml
  test/spec/crud/unified/findOneAndReplace-comment.json
  test/spec/crud/unified/findOneAndReplace-comment.yml
  test/spec/crud/unified/findOneAndUpdate-comment.json
  test/spec/crud/unified/findOneAndUpdate-comment.yml
  test/spec/crud/unified/insertMany-comment.json
  test/spec/crud/unified/insertMany-comment.yml
  test/spec/crud/unified/insertOne-comment.json
  test/spec/crud/unified/insertOne-comment.yml
  test/spec/crud/unified/replaceOne-comment.json
  test/spec/crud/unified/replaceOne-comment.yml
  test/spec/crud/unified/updateMany-comment.json
  test/spec/crud/unified/updateMany-comment.yml
  test/spec/crud/unified/updateOne-comment.json
  test/spec/crud/unified/updateOne-comment.yml
  test/tools/unified-spec-runner/entities.ts
  test/tools/unified-spec-runner/match.ts
  test/tools/unified-spec-runner/operations.ts
  test/tools/unified-spec-runner/schema.ts
  test/tools/utils.ts
  test/unit/connection_string.test.ts
  test/unit/operations/get_more.test.js
  test/unit/operations/get_more.test.ts
  test/unit/operations/list_collections.test.js
Labels: Team Review

#3180 fix(NODE-3810): delay timeout errors by one event loop tick
  .gitignore
  src/cmap/commands.ts
  src/cmap/connection.ts
  src/index.ts
  test/tools/runner/hooks/configuration.js
  test/unit/cmap/connection.test.js
  test/unit/cmap/connection.test.ts
Labels: Team Review

#3185 chore(NODE-4153): make type fixes for ts 4.7
  .evergreen/config.yml
  .evergreen/config.yml.in
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-lint-checks.sh
  .evergreen/run-typescript.sh
  .evergreen/run-unit-tests.sh
  README.md
  package-lock.json
  package.json
  src/change_stream.ts
  src/cmap/connection.ts
  src/cmap/stream_description.ts
  src/collection.ts
  src/cursor/abstract_cursor.ts
  src/cursor/aggregation_cursor.ts
  src/cursor/find_cursor.ts
  src/db.ts
  src/encrypter.ts
  src/error.ts
  src/sdam/events.ts
  src/sdam/monitor.ts
  src/sdam/server.ts
  src/utils.ts
  test/types/community/collection/insertX.test-d.ts
Labels: Team Review

#3184 fix(NODE-4133): array field NestedPaths return type
  src/mongo_types.ts
  test/types/community/collection/filterQuery.test-d.ts
Labels: Team Review, External Submission

#3187 test(NODE-4082): session spec prose test language clean up
  test/integration/sessions/sessions.spec.prose.test.ts
Labels: Team Review

#3159 test(NODE-4057): update dns discovery tests
  test/integration/initial-dns-seedlist-discovery/initial_dns_seedlist_discovery.spec.test.ts
  test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-directConnection.json
  test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-directConnection.yml
  test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-replicaSet-errors.json
  test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-replicaSet-errors.yml
  test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-true-txt.json
  test/spec/initial-dns-seedlist-discovery/load-balanced/loadBalanced-true-txt.yml
  test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true-txt.json
  test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-conflicts_with_loadBalanced-true-txt.yml
  test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero-txt.json
  test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero-txt.yml
  test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero.json
  test/spec/initial-dns-seedlist-discovery/load-balanced/srvMaxHosts-zero.yml
Labels: Team Review

#3192 test(NODE-4152): convert cmap test runner to ts and decouple from test context
  test/tools/cmap_spec_runner.ts
  test/tools/utils.ts
  test/unit/assorted/connection_monitoring_and_pooling.spec.test.js
  test/unit/assorted/connection_monitoring_and_pooling.spec.test.ts
Labels: Team Review

#3182 test(NODE-4157): SDAM unit test typescript and improvements
  package-lock.json
  package.json
  src/sdam/topology_description.ts
  test/spec/server-discovery-and-monitoring/rs/secondary_ignore_ok_0.json
  test/spec/server-discovery-and-monitoring/rs/secondary_ignore_ok_0.yml
  test/tools/utils.ts
  test/unit/assorted/server_discovery_and_monitoring.spec.test.js
  test/unit/assorted/server_discovery_and_monitoring.spec.test.ts
Labels: Team Review

#3189 chore(NODE-4075): add docs generation workflow
  .github/workflows/build_docs.yml
Labels: Team Review

#3195 fix(NODE-4156): remove comment from commands pre-4.4
  src/operations/command.ts
  test/integration/enumerate_collections.test.ts
  test/integration/enumerate_databases.test.ts
  test/integration/enumerate_indexes.test.ts
  test/tools/unified-spec-runner/match.ts
Labels: Team Review

#3193 fix(NODE-4031): options parsing for array options
  src/connection_string.ts
  test/unit/connection_string.test.ts
Labels: Team Review

#3196 chore(NODE-4177): remove unused Server.query method
  src/cmap/connection.ts
  src/operations/find.ts
  src/sdam/server.ts
Labels: Primary Review

#3202 test(NODE-4152): make connect auth check configurable
  .evergreen/config.yml
  .evergreen/config.yml.in
  src/connection_string.ts
  src/mongo_client.ts
  src/operations/execute_operation.ts
  src/sdam/topology.ts
  test/integration/node-specific/feature_flags.test.ts
  test/tools/spec-runner/index.js
  test/tools/unified-spec-runner/entities.ts
  test/unit/assorted/scram_iterations.test.ts
  test/unit/connection_string.test.ts
Labels: Primary Review

#3201 refactor(NODE-2992): clean up server selection logic runner
  test/unit/assorted/server_selection.spec.test.js
  test/unit/assorted/server_selection.spec.test.ts
  test/unit/assorted/server_selection_logic_spec_utils.ts
  test/unit/assorted/server_selection_spec_helper.js
Labels: Primary Review

#3199 fix(NODE-3928): don't throw error in Response constructor
  src/cmap/commands.ts
  test/unit/cmap/commands.test.js
Labels: Team Review

#3205 chore(NODE-3723): add node 16 to ci
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/init-nvm.sh
  .evergreen/install-dependencies.sh
  .evergreen/run-atlas-tests.sh
  .evergreen/run-socks5-tests.sh
Labels: Team Review

#3206 feat(NODE-4136): revise FLE shared library typings for spec changes
  src/deps.ts
Labels: Team Review

#3208 chore(NODE-4171): add timestamp breaking change to 4_0_0 migration notes
  etc/notes/CHANGES_4.0.0.md
Labels: Team Review

#3215 refactor(NODE-4059): move free functions into ChangeStream class
  src/change_stream.ts
  src/constants.ts
  src/error.ts
  src/index.ts
  src/utils.ts
  test/unit/error.test.ts
Labels: Team Review
