Repository mongodb/node-mongodb-native, pull requests merged in 2022-05, with the labels that each got.

#3225 fix(NODE-4208): add aws http request timeout handler
  .evergreen/config.in.yml
  .evergreen/config.yml
  src/cmap/auth/mongodb_aws.ts
  src/error.ts
  src/index.ts
  test/integration/auth/mongodb_aws.test.js
Labels: Team Review

#3218 feat(NODE-4202): add FLE 2 behavior for create/drop collection
  src/encrypter.ts
  src/operations/create_collection.ts
  src/operations/drop.ts
  test/spec/client-side-encryption/tests/fle2-CreateCollection.json
  test/spec/client-side-encryption/tests/fle2-CreateCollection.yml
  test/spec/client-side-encryption/tests/noSchema.json
  test/spec/client-side-encryption/tests/noSchema.yml
  test/tools/spec-runner/index.js
Labels: Team Review

#3227 test(NODE-4216): add 6.0 server to CI matrix
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
Labels: Team Review

#3191 feat(NODE-4059): ChangeStreamDocument not fully typed to specification
  src/change_stream.ts
  src/collection.ts
  src/db.ts
  src/index.ts
  src/mongo_client.ts
  test/integration/change-streams/change_stream.test.ts
  test/tools/unified-spec-runner/operations.ts
  test/tools/utils.ts
  test/types/change_stream.test-d.ts
  test/types/mongodb.test-d.ts
Labels: Team Review

#3230 feat(NODE-4185): Allow opting out of disk use on cursor builder
  src/cursor/find_cursor.ts
  test/integration/crud/find_cursor_methods.test.js
Labels: Team Review

#3229 feat(NODE-4189): Support clustered collections
  src/index.ts
  src/operations/create_collection.ts
  test/spec/collection-management/clustered-indexes.json
  test/spec/collection-management/clustered-indexes.yml
Labels: Team Review

#3221 fix(NODE-3565): Error for insertMany with partially empty array is unhelpful
  src/bulk/common.ts
  src/operations/insert.ts
  test/integration/crud/bulk.test.js
Labels: Team Review

#3234 fix(NODE-4232): stream() also returns generic AsyncIterable
  src/change_stream.ts
  src/cursor/abstract_cursor.ts
  test/types/community/cursor.test-d.ts
Labels: tracked-in-jira, Team Review

#3239 test(NODE-4165): sync maxConnecting spec tests and update runner
  test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.spec.test.ts
  test/spec/connection-monitoring-and-pooling/pool-checkout-maxConnecting-is-enforced.json
  test/spec/connection-monitoring-and-pooling/pool-checkout-maxConnecting-is-enforced.yml
  test/spec/connection-monitoring-and-pooling/pool-checkout-maxConnecting-timeout.json
  test/spec/connection-monitoring-and-pooling/pool-checkout-maxConnecting-timeout.yml
  test/spec/connection-monitoring-and-pooling/pool-checkout-minPoolSize-connection-maxConnecting.json
  test/spec/connection-monitoring-and-pooling/pool-checkout-minPoolSize-connection-maxConnecting.yml
  test/spec/connection-monitoring-and-pooling/pool-checkout-returned-connection-maxConnecting.json
  test/spec/connection-monitoring-and-pooling/pool-checkout-returned-connection-maxConnecting.yml
  test/tools/cmap_spec_runner.ts
  test/unit/assorted/connection_monitoring_and_pooling.spec.test.ts
Labels: Team Review

#3233 test(NODE-3248): sync new unified change stream tests & enhance runner
  test/integration/change-streams/change_streams.spec.test.ts
  test/spec/change-streams/unified/change-streams-errors.json
  test/spec/change-streams/unified/change-streams-errors.yml
  test/spec/change-streams/unified/change-streams-resume-allowlist.json
  test/spec/change-streams/unified/change-streams-resume-allowlist.yml
  test/spec/change-streams/unified/change-streams-resume-errorLabels.json
  test/spec/change-streams/unified/change-streams-resume-errorLabels.yml
  test/spec/change-streams/unified/change-streams.json
  test/spec/change-streams/unified/change-streams.yml
  test/spec/unified-test-format/invalid/expectedEventsForClient-ignoreExtraEvents-type.json
  test/spec/unified-test-format/invalid/expectedEventsForClient-ignoreExtraEvents-type.yml
  test/spec/unified-test-format/valid-pass/expectedEventsForClient-ignoreExtraEvents.json
  test/spec/unified-test-format/valid-pass/expectedEventsForClient-ignoreExtraEvents.yml
  test/tools/unified-spec-runner/match.ts
  test/tools/unified-spec-runner/operations.ts
  test/tools/unified-spec-runner/runner.ts
  test/tools/unified-spec-runner/schema.ts
Labels: Team Review

#3236 fix(NODE-4108): improve return type for withTransaction()
  global.d.ts
  src/sessions.ts
  src/transactions.ts
  test/integration/transactions/transactions.test.ts
Labels: Team Review

#3244 feat(NODE-4079): estimated document count uses count
  src/collection.ts
  src/operations/estimated_document_count.ts
  test/integration/collection-management/collection.test.js
  test/integration/read-write-concern/readconcern.test.js
  test/spec/atlas-data-lake-testing/estimatedDocumentCount.json
  test/spec/atlas-data-lake-testing/estimatedDocumentCount.yml
  test/spec/crud/unified/estimatedDocumentCount.json
  test/spec/crud/unified/estimatedDocumentCount.yml
  test/spec/retryable-reads/legacy/estimatedDocumentCount-4.9.json
  test/spec/retryable-reads/legacy/estimatedDocumentCount-pre4.9.yml
  test/spec/retryable-reads/legacy/estimatedDocumentCount-serverErrors-4.9.json
  test/spec/retryable-reads/legacy/estimatedDocumentCount-serverErrors-pre4.9.yml
  test/spec/retryable-reads/legacy/estimatedDocumentCount-serverErrors.json
  test/spec/retryable-reads/legacy/estimatedDocumentCount-serverErrors.yml
  test/spec/retryable-reads/legacy/estimatedDocumentCount.json
  test/spec/retryable-reads/legacy/estimatedDocumentCount.yml
  test/spec/versioned-api/crud-api-version-1-strict.json
  test/spec/versioned-api/crud-api-version-1-strict.yml
  test/spec/versioned-api/crud-api-version-1.json
  test/spec/versioned-api/crud-api-version-1.yml
Labels: Team Review

#3250 feat(NODE-3938): Add support for pre/post images in change streams
  src/change_stream.ts
  src/operations/create_collection.ts
  test/integration/collection-management/collection_management.spec.test.js
  test/spec/change-streams/unified/change-streams-pre_and_post_images.json
  test/spec/change-streams/unified/change-streams-pre_and_post_images.yml
  test/spec/collection-management/clustered-indexes.json
  test/spec/collection-management/clustered-indexes.yml
  test/spec/collection-management/createCollection-pre_and_post_images.json
  test/spec/collection-management/createCollection-pre_and_post_images.yml
  test/spec/collection-management/modifyCollection-pre_and_post_images.json
  test/spec/collection-management/modifyCollection-pre_and_post_images.yml
Labels: Team Review

#3237 feat(NODE-1837): add zstd compression option
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-tests.sh
  package-lock.json
  package.json
  src/cmap/wire_protocol/compression.ts
  src/deps.ts
  test/tools/runner/hooks/configuration.js
  test/types/community/changes_from_36.test-d.ts
  test/unit/cmap/wire_protocol/compression.test.ts
Labels: Team Review

#3255 feat(NODE-2993): implement maxConnecting
  src/cmap/connection_pool.ts
  src/cmap/connection_pool_events.ts
  test/integration/connection-monitoring-and-pooling/cmap-node-specs/pool-minPoolSize-population-stats.json
  test/integration/connection-monitoring-and-pooling/cmap-node-specs/pool-minPoolSize-replace-removed-connections.json
  test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.spec.test.ts
  test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.test.ts
  test/tools/cmap_spec_runner.ts
Labels: Team Review

#3256 feat(NODE-4139): streaming protocol message changes
  src/cmap/connection.ts
  src/cmap/message_stream.ts
  src/sdam/monitor.ts
  test/tools/utils.ts
  test/unit/cmap/message_stream.test.js
  test/unit/sdam/monitor.test.js
Labels: Team Review

#3260 fix(NODE-4254): allow csfle to be dynamically required
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  src/encrypter.ts
Labels: Primary Review

#3251 refactor(NODE-4246): update FLE2 collection management
  src/operations/create_collection.ts
  src/operations/drop.ts
  test/spec/client-side-encryption/tests/fle2-CreateCollection.json
  test/spec/client-side-encryption/tests/fle2-CreateCollection.yml
Labels: Team Review

#3265 feat(NODE-4229): bump maxWireVersion to 17
  src/cmap/wire_protocol/constants.ts
  test/unit/assorted/wire_version.test.js
  test/unit/cmap/wire_protocol/constants.test.js
Labels: Primary Review

#3268 chore: update typescript version
  package-lock.json
  package.json
Labels: Primary Review

#3261 feat(NODE-3750): make maxConnecting configurable
  src/cmap/connection_pool.ts
  src/connection_string.ts
  src/mongo_client.ts
  test/spec/connection-monitoring-and-pooling/pool-checkout-custom-maxConnecting-is-enforced.json
  test/spec/connection-monitoring-and-pooling/pool-checkout-custom-maxConnecting-is-enforced.yml
  test/spec/uri-options/connection-pool-options.json
  test/spec/uri-options/connection-pool-options.yml
  test/tools/cmap_spec_runner.ts
  test/tools/uri_spec_runner.ts
  test/unit/mongo_client.test.js
Labels: Team Review

#3272 test: improve change stream tests
  src/change_stream.ts
  test/integration/change-streams/change_stream.test.ts
Labels: Team Review

#3270 feat(NODE-4081): fix and deprecate change stream resume options
  src/change_stream.ts
  test/unit/change_stream.test.ts
Labels: Team Review
