Repository mongodb/node-mongodb-native, pull requests merged in 2022-10, with the labels that each got.

#3425 fix(NODE-4186): accept ReadPreferenceLike in TransactionOptions type
  src/transactions.ts
  test/types/community/transaction.test-d.ts
  test/unit/transactions.test.ts
Labels: Team Review, External Submission

#3405 fix(NODE-3921): error on invalid TLS option combinations
  src/connection_string.ts
  test/unit/assorted/uri_options.spec.test.ts
Labels: Team Review, External Submission

#3404 fix(NODE-4608): prevent parallel monitor checks
  src/sdam/monitor.ts
  test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.spec.test.ts
Labels: Team Review

#3427 ci(NODE-4651): add Node.js 18
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  test/integration/client-side-encryption/client_side_encryption.prose.corpus.test.js
  test/integration/client-side-encryption/client_side_encryption.prose.deadlock.js
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
  test/integration/client-side-encryption/client_side_encryption.spec.test.ts
  test/integration/client-side-encryption/driver.test.ts
  test/integration/crud/misc_cursors.test.js
  test/integration/node-specific/ipv6.test.ts
  test/integration/server-selection/server_selection.prose.operation_count.test.ts
  test/tools/mongodb-mock/src/server.js
  test/tools/runner/hooks/configuration.js
Labels: Team Review

#3432 feat(NODE-3651): add hashed index type
  src/operations/indexes.ts
  test/types/community/createIndex.test-d.ts
Labels: External Submission

#3434 test(NODE-4628, NODE-4640): sync fle and change stream spec tests
  test/spec/change-streams/unified/change-streams-clusterTime.json
  test/spec/change-streams/unified/change-streams-clusterTime.yml
  test/spec/change-streams/unified/change-streams-showExpandedEvents.json
  test/spec/change-streams/unified/change-streams-showExpandedEvents.yml
  test/spec/client-side-encryption/tests/legacy/maxWireVersion.json
  test/spec/client-side-encryption/tests/legacy/maxWireVersion.yml
Labels: Team Review

#3440 refactor(NODE-4689): track checked out connections
  src/cmap/connection_pool.ts
Labels: Team Review

#3445 docs: Note special case in `AbstractCursor.forEach()` iterator
  src/cursor/abstract_cursor.ts
Labels: tracked-in-jira, Team Review, External Submission

#3433 feat(NODE-3875): support recursive schema types
  src/mongo_types.ts
  test/types/basic_schema.test-d.ts
  test/types/community/collection/findX-recursive-types.test-d.ts
  test/types/community/collection/recursive-types.test-d.ts
  test/types/community/collection/updateX.test-d.ts
  test/types/community/slow-model.test-d.ts
  test/types/union_schema.test-d.ts
Labels: Team Review

#3437 fix(NODE-4475): make interrupted message more specific
  src/cursor/abstract_cursor.ts
  test/integration/change-streams/change_stream.test.ts
Labels: Team Review

#3446 feat(NODE-4721): add aws-sdk as optional dependency
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/install-dependencies.sh
  package-lock.json
  package.json
  src/cmap/auth/mongodb_aws.ts
  src/deps.ts
  test/integration/auth/mongodb_aws.test.ts
Labels: Team Review

#3439 chore(NODE-4700): update dependencies
  package-lock.json
  package.json
  test/tools/runner/hooks/leak_checker.ts
  test/unit/assorted/imports.test.ts
Labels: Primary Review

#3448 docs(NODE-4724): update fle docs to use "in use encryption" terminology
  src/collection.ts
  src/deps.ts
  src/error.ts
  src/mongo_client.ts
  src/sdam/topology.ts
Labels: Team Review

#3443 refactor(NODE-4690): update cmap and test runners to support interruptInUseConnections
  src/cmap/connection_pool.ts
  src/cmap/connection_pool_events.ts
  test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.spec.test.ts
  test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.spec.test.ts
  test/spec/connection-monitoring-and-pooling/pool-clear-interrupt-immediately.json
  test/spec/connection-monitoring-and-pooling/pool-clear-interrupt-immediately.yml
  test/spec/connection-monitoring-and-pooling/pool-clear-interrupting-pending-connections.json
  test/spec/connection-monitoring-and-pooling/pool-clear-interrupting-pending-connections.yml
  test/spec/connection-monitoring-and-pooling/pool-clear-schedule-run-interruptInUseConnections-false.json
  test/spec/connection-monitoring-and-pooling/pool-clear-schedule-run-interruptInUseConnections-false.yml
  test/spec/server-discovery-and-monitoring/unified/interruptInUse-pool-clear.json
  test/spec/server-discovery-and-monitoring/unified/interruptInUse-pool-clear.yml
  test/spec/unified-test-format/invalid/expectedCmapEvent-poolClearedEvent-interruptInUseConnections-type.json
  test/spec/unified-test-format/invalid/expectedCmapEvent-poolClearedEvent-interruptInUseConnections-type.yml
  test/tools/cmap_spec_runner.ts
  test/tools/unified-spec-runner/match.ts
  test/tools/unified-spec-runner/schema.ts
Labels: Team Review

#3375 test(NODE-3897): re-enable combined coverage
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/prepare-shell.sh
Labels: Team Review

#3447 perf(NODE-4727): Improve performance of buffering and cursors
  package-lock.json
  package.json
  src/cmap/connection_pool.ts
  src/cmap/message_stream.ts
  src/cursor/abstract_cursor.ts
  src/index.ts
  src/sdam/topology.ts
  src/sessions.ts
  src/utils.ts
  test/action/dependency.test.ts
  test/benchmarks/unitBench/list.bench.js
  test/integration/crud/find_cursor_methods.test.js
  test/unit/sessions.test.js
  test/unit/utils.test.ts
Labels: Team Review

#3442 ci(NODE-4629): run csfle tests on serverless
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/run-serverless-tests.sh
  test/integration/client-side-encryption/client_side_encryption.spec.test.ts
  test/spec/client-side-encryption/tests/legacy/fle2-BypassQueryAnalysis.json
  test/spec/client-side-encryption/tests/legacy/fle2-BypassQueryAnalysis.yml
  test/spec/client-side-encryption/tests/legacy/fle2-Compact.json
  test/spec/client-side-encryption/tests/legacy/fle2-Compact.yml
  test/spec/client-side-encryption/tests/legacy/fle2-CreateCollection.json
  test/spec/client-side-encryption/tests/legacy/fle2-CreateCollection.yml
  test/spec/client-side-encryption/tests/legacy/fle2-DecryptExistingData.json
  test/spec/client-side-encryption/tests/legacy/fle2-DecryptExistingData.yml
  test/spec/client-side-encryption/tests/legacy/fle2-Delete.json
  test/spec/client-side-encryption/tests/legacy/fle2-Delete.yml
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.json
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.yml
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-jsonSchema.json
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-jsonSchema.yml
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFieldsMap-defaults.json
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFieldsMap-defaults.yml
  test/spec/client-side-encryption/tests/legacy/fle2-FindOneAndUpdate.json
  test/spec/client-side-encryption/tests/legacy/fle2-FindOneAndUpdate.yml
  test/spec/client-side-encryption/tests/legacy/fle2-InsertFind-Indexed.json
  test/spec/client-side-encryption/tests/legacy/fle2-InsertFind-Indexed.yml
  test/spec/client-side-encryption/tests/legacy/fle2-InsertFind-Unindexed.json
  test/spec/client-side-encryption/tests/legacy/fle2-InsertFind-Unindexed.yml
  test/spec/client-side-encryption/tests/legacy/fle2-MissingKey.json
  test/spec/client-side-encryption/tests/legacy/fle2-MissingKey.yml
  test/spec/client-side-encryption/tests/legacy/fle2-NoEncryption.json
  test/spec/client-side-encryption/tests/legacy/fle2-NoEncryption.yml
  test/spec/client-side-encryption/tests/legacy/fle2-Update.json
  test/spec/client-side-encryption/tests/legacy/fle2-Update.yml
  test/spec/client-side-encryption/tests/legacy/fle2-validatorAndPartialFieldExpression.json
  test/spec/client-side-encryption/tests/legacy/fle2-validatorAndPartialFieldExpression.yml
Labels: Team Review

#3452 fix(NODE-4609): allow mapping to falsey non-null values in cursors
  src/cursor/abstract_cursor.ts
  test/integration/node-specific/abstract_cursor.test.ts
Labels: Team Review

#3455 refactor(NODE-4754): remove unused QueryOptions export
  src/cmap/connection.ts
  src/index.ts
Labels: Team Review

#3453 fix(NODE-4735): fix change stream consecutive resumabilty
  src/change_stream.ts
  test/integration/change-streams/change_stream.test.ts
  test/integration/change-streams/change_streams.spec.test.ts
  test/integration/unified-test-format/unified_test_format.spec.test.ts
Labels: Team Review
