Repository mongodb/node-mongodb-native, pull requests merged in 2022-07, with the labels that each got.

#3305 test(NODE-4260): add test for csfle bulk write error
  test/integration/client-side-encryption/driver.test.js
Labels: Team Review

#3302 test(NODE-4382): update fle setup in test readme
  test/readme.md
Labels: Primary Review

#3299 test(NODE-4347): add coverage for auto connecting operations
  src/collection.ts
  src/cursor/list_collections_cursor.ts
  src/cursor/list_indexes_cursor.ts
  src/db.ts
  src/index.ts
  src/operations/indexes.ts
  src/operations/list_collections.ts
  test/integration/node-specific/auto_connect.test.ts
  test/types/list_collections.test-d.ts
Labels: Team Review

#3309 test(NODE-4282): sync fle2 payload spec test updates
  .evergreen/run-custom-csfle-tests.sh
  .evergreen/run-tests.sh
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
  test/integration/client-side-encryption/driver.test.js
  test/spec/client-side-encryption/tests/legacy/fle2-Delete.json
  test/spec/client-side-encryption/tests/legacy/fle2-Delete.yml
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-jsonSchema.json
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-jsonSchema.yml
  test/spec/client-side-encryption/tests/legacy/fle2-FindOneAndUpdate.json
  test/spec/client-side-encryption/tests/legacy/fle2-FindOneAndUpdate.yml
  test/spec/client-side-encryption/tests/legacy/fle2-InsertFind-Indexed.json
  test/spec/client-side-encryption/tests/legacy/fle2-InsertFind-Indexed.yml
  test/spec/client-side-encryption/tests/legacy/fle2-Update.json
  test/spec/client-side-encryption/tests/legacy/fle2-Update.yml
Labels: Team Review

#3314 test(NODE-4363): Add support for ClientEncryption in the unified test runner
  src/encrypter.ts
  src/utils.ts
  test/integration/client-side-encryption/client_side_encryption.spec.test.ts
  test/integration/unified-test-format/unified_test_format.spec.test.ts
  test/readme.md
  test/tools/unified-spec-runner/entities.ts
  test/tools/unified-spec-runner/match.ts
  test/tools/unified-spec-runner/operations.ts
  test/tools/unified-spec-runner/schema.ts
  test/tools/unified-spec-runner/unified-utils.ts
  test/unit/tools/unifed-utils.test.ts
Labels: Team Review

#3317 refactor(NODE-4392): getMore and killCursors methods
  src/cmap/command_monitoring_events.ts
  src/cmap/commands.ts
  src/cmap/connection.ts
  src/cmap/message_stream.ts
  src/cmap/wire_protocol/constants.ts
  src/index.ts
  src/operations/get_more.ts
  src/operations/kill_cursors.ts
  src/sdam/server.ts
  src/utils.ts
  test/integration/change-streams/change_stream.test.ts
  test/integration/server-selection/operation_count.test.ts
  test/unit/cmap/command_monitoring_events.test.js
  test/unit/operations/get_more.test.ts
  test/unit/operations/kill_cursors.test.ts
  test/unit/utils.test.ts
Labels: Team Review

#3327 fix(NODE-4444): use Node.js clear timers
  .eslintrc.json
  src/cmap/connection.ts
  src/cmap/connection_pool.ts
  src/sdam/common.ts
  src/sdam/monitor.ts
  src/sdam/srv_polling.ts
  src/sdam/topology.ts
  src/utils.ts
  test/integration/objectid.test.js
  test/unit/sdam/topology.test.js
Labels: Team Review

#3324 fix(NODE-4425): webpack optional import of FLE issue
  src/encrypter.ts
  src/utils.ts
  test/tools/unified-spec-runner/unified-utils.ts
Labels: Team Review

#3326 chore(NODE-4431): fix failing change stream tests & csfle tests on windows
  test/integration/change-streams/change_stream.test.ts
  test/integration/change-streams/change_streams.spec.test.ts
  test/readme.md
  test/tools/unified-spec-runner/runner.ts
  test/tools/unified-spec-runner/schema.ts
  test/tools/unified-spec-runner/unified-utils.ts
Labels: Team Review

#3325 test: fix aws auth tests
  package.json
  test/integration/auth/mongodb_aws.test.ts
Labels: Team Review

#3328 fix(NODE-4423): better type support for nested objects in query & update
  src/mongo_types.ts
  test/types/community/collection/filterQuery.test-d.ts
  test/types/community/collection/updateX.test-d.ts
Labels: Team Review, External Submission

#3315 feat(NODE-3517): improve index spec handling and type definitions
  src/cmap/connection.ts
  src/operations/indexes.ts
  src/utils.ts
  test/integration/client-side-encryption/driver.test.js
  test/integration/client-side-encryption/driver.test.ts
  test/tools/spec-runner/index.js
  test/tools/spec-runner/matcher.js
  test/tools/unified-spec-runner/match.ts
  test/tools/unified-spec-runner/operations.ts
  test/tools/unified-spec-runner/runner.ts
  test/tools/unified-spec-runner/schema.ts
  test/types/community/createIndex.test-d.ts
  test/unit/operations/indexes.test.ts
Labels: Team Review

#3331 test(NODE-4434): sync skipped StaleShardVersion change stream unifed tests
  test/integration/change-streams/change_streams.spec.test.ts
  test/spec/change-streams/unified/change-streams-resume-errorLabels.json
  test/spec/change-streams/unified/change-streams-resume-errorLabels.yml
Labels: Team Review

#3334 test(NODE-4395): add csfle master && pinned commit tasks to CI
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-custom-csfle-tests.sh
Labels: Team Review

#3340 feat(NODE-4336): deprecate old write concern options and add missing writeConcern to MongoClientOptions
  src/connection_string.ts
  src/mongo_client.ts
  test/types/mongodb.test-d.ts
Labels: Team Review

#3335 test(NODE-4331): add prose test 13
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
Labels: Team Review

#3333 test(NODE-4463): download shared lib in evergreen
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/prepare-crypt-shared-lib.sh
  .evergreen/run-custom-csfle-tests.sh
  test/readme.md
Labels: Team Review
