Repository mongodb/node-mongodb-native, pull requests merged in 2022-08, with the labels that each got.

#3337 fix(NODE-4467): Add back support for `oplogReplay` option as deprecated
  src/operations/find.ts
  test/unit/operations/find.test.ts
Labels: tracked-in-jira, Team Review

#3341 test(NODE-4487, NODE-4390): sync key management tests && bump fle version in tests
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-bson-ext-test.sh
  .evergreen/run-tests.sh
  test/spec/client-side-encryption/tests/unified/addKeyAltName.json
  test/spec/client-side-encryption/tests/unified/addKeyAltName.yml
  test/spec/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.json
  test/spec/client-side-encryption/tests/unified/createDataKey-kms_providers-invalid.yml
  test/spec/client-side-encryption/tests/unified/getKey.json
  test/spec/client-side-encryption/tests/unified/getKey.yml
  test/spec/client-side-encryption/tests/unified/getKeyByAltName.json
  test/spec/client-side-encryption/tests/unified/getKeyByAltName.yml
  test/spec/client-side-encryption/tests/unified/removeKeyAltName.json
  test/spec/client-side-encryption/tests/unified/removeKeyAltName.yml
  test/spec/client-side-encryption/tests/unified/rewrapManyDataKey.json
  test/spec/client-side-encryption/tests/unified/rewrapManyDataKey.yml
Labels: Team Review

#3343 chore(NODE-4500): fix npm issue on windows
  .evergreen/install-dependencies.sh
Labels: Primary Review

#3339 fix(NODE-4273): pass 'comment' option through to distinct command
  src/operations/distinct.ts
  test/integration/node-specific/comment_with_falsy_values.test.ts
  test/spec/crud/unified/distinct-comment.json
  test/spec/crud/unified/distinct-comment.yml
Labels: Team Review

#3342 fix(NODE-4496): counter values incorrecly compared when instance of Long
  src/bulk/common.ts
  src/cursor/abstract_cursor.ts
  src/sdam/monitor.ts
  src/sdam/server_description.ts
  src/sdam/topology_description.ts
  src/sessions.ts
  src/utils.ts
  test/unit/sdam/server_description.test.js
  test/unit/sdam/server_description.test.ts
Labels: Team Review

#3348 fix(NODE-4159,NODE-4512): remove servers with incorrect setName from topology and fix unix socket parsing
  src/sdam/server.ts
  src/sdam/server_description.ts
  src/sdam/topology.ts
  src/sdam/topology_description.ts
  src/utils.ts
  test/unit/assorted/server_discovery_and_monitoring.spec.test.ts
  test/unit/operations/find.test.ts
  test/unit/operations/get_more.test.ts
  test/unit/operations/kill_cursors.test.ts
  test/unit/sdam/server_description.test.ts
  test/unit/utils.test.ts
Labels: Team Review

#3345 test(NODE-4489): add CSFLE prose test 16
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
Labels: Team Review

#3319 fix(NODE-4413): set maxTimeMS on getMores when maxAwaitTimeMS is specified
  src/cursor/abstract_cursor.ts
  src/operations/get_more.ts
  test/integration/change-streams/change_stream.test.ts
  test/integration/crud/maxTimeMS.test.ts
  test/integration/crud/maxtimems.test.js
  test/unit/operations/get_more.test.ts
Labels: Team Review

#3338 test(NODE-4483): set crypt shared lib path
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/run-custom-csfle-tests.sh
  test/tools/runner/hooks/configuration.js
  test/tools/spec-runner/index.js
  test/tools/unified-spec-runner/unified-utils.ts
Labels: Team Review

#3354 test(NODE-4422): use shared lib in prose tests
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/prepare-crypt-shared-lib.sh
  test/integration/client-side-encryption/client_side_encryption.prose.corpus.test.js
  test/integration/client-side-encryption/client_side_encryption.prose.deadlock.js
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
  test/integration/client-side-encryption/driver.test.ts
  test/tools/utils.ts
Labels: Primary Review

#3359 test(NODE-3735): update to use serverless uri
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/run-serverless-tests.sh
  test/readme.md
  test/tools/runner/config.ts
Labels: Team Review

#3361 test(NODE-4333): add unit test to check dependencies
  .github/workflows/dependencies.yml
  package.json
  test/unit/dependency.test.ts
Labels: Team Review

#3355 fix(NODE-4533): session support error message and unified test runner
  src/sessions.ts
  test/tools/unified-spec-runner/entities.ts
  test/tools/unified-spec-runner/match.ts
  test/tools/unified-spec-runner/operations.ts
  test/tools/unified-spec-runner/runner.ts
  test/tools/unified-spec-runner/unified-utils.ts
  test/unit/sessions.test.js
Labels: Team Review

#3349 fix(NODE-4513): type for nested objects in query & update
  src/index.ts
  src/mongo_types.ts
  test/types/community/collection/filterQuery.test-d.ts
Labels: Team Review, External Submission

#3363 fix(NODE-4429): select server sync for endSessions during close
  src/mongo_client.ts
  test/integration/node-specific/mongo_client.test.ts
Labels: Team Review

#3367 fix(NODE-4555): export BSON internally
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  src/bson.ts
  src/index.ts
Labels: Team Review

#3366 test(NODE-4553): move check test to action folder
  package.json
  test/action/dependency.test.ts
  test/readme.md
Labels: Primary Review

#3357 feat(NODE-4548): export ChangeStream class from top-level
  src/collection.ts
  src/index.ts
Labels: Team Review

#3379 test(NODE-4574): skip zstd and snappy on gallium
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
Labels: Team Review

#3378 test(NODE-4479): adjust number of iterations of flakey test
  test/integration/server-selection/server_selection.prose.operation_count.test.ts
Labels: Team Review

#3380 test(NODE-4200): sync serverless:forbid changes in change stream unified tests
  test/spec/change-streams/unified/change-streams-errors.json
  test/spec/change-streams/unified/change-streams-errors.yml
  test/spec/change-streams/unified/change-streams-pre_and_post_images.json
  test/spec/change-streams/unified/change-streams-pre_and_post_images.yml
  test/spec/change-streams/unified/change-streams-resume-allowlist.json
  test/spec/change-streams/unified/change-streams-resume-allowlist.yml
  test/spec/change-streams/unified/change-streams-resume-errorLabels.json
  test/spec/change-streams/unified/change-streams-resume-errorLabels.yml
  test/spec/change-streams/unified/change-streams.json
  test/spec/change-streams/unified/change-streams.yml
  test/spec/unified-test-format/valid-pass/poc-change-streams.json
  test/spec/unified-test-format/valid-pass/poc-change-streams.yml
Labels: Team Review

#3383 fix(NODE-4583): revert nested union type support
  src/index.ts
  src/mongo_types.ts
  test/types/community/collection/filterQuery.test-d.ts
Labels: Team Review

#3381 test(NODE-4562): reduce macos coverage
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
Labels: Team Review

#3387 chore(NODE-4593): fix mongosh integration tests
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-mongosh-integration-tests.sh
Labels: Primary Review

#3385 ci(NODE-4589): add benchmark testing task to CI
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/run-benchmarks.sh
  test/benchmarks/driverBench/common.js
  test/benchmarks/driverBench/index.js
  test/benchmarks/mongoBench/benchmark.js
  test/benchmarks/mongoBench/constants.js
  test/benchmarks/mongoBench/index.js
  test/benchmarks/mongoBench/runner.js
  test/benchmarks/mongoBench/suite.js
  test/benchmarks/mongoBench/util.js
Labels: Team Review

#3369 test(NODE-4160): add aws lambda examples
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-lambda-aws-tests.sh
  .evergreen/run-lambda-tests.sh
  package.json
  test/integration/node-specific/examples/aws_handler.js
  test/integration/node-specific/examples/aws_handler.test.js
  test/integration/node-specific/examples/handler.js
  test/integration/node-specific/examples/handler.test.js
  test/integration/node-specific/examples/setup.js
  test/mocha_lambda.json
  test/mocha_mongodb.json
  test/readme.md
Labels: Team Review
