Repository mongodb/node-mongodb-native, pull requests merged in 2022-09, with the labels that each got.

#3390 fix(NODE-4557): randomize servers when there are only 2 eligible servers
  src/sdam/topology.ts
  test/integration/server-selection/server_selection.prose.operation_count.test.ts
Labels: Team Review

#3393 test(NODE-4585): ensure empty aws env variables
  .evergreen/config.in.yml
  .evergreen/config.yml
Labels: Team Review

#3321 feat(NODE-4385): add cmap pool pausing functionality
  src/cmap/connection_pool.ts
  src/cmap/connection_pool_events.ts
  src/cmap/errors.ts
  src/constants.ts
  src/error.ts
  src/index.ts
  src/sdam/monitor.ts
  src/sdam/server.ts
  src/sdam/server_description.ts
  src/sdam/topology.ts
  test/integration/connection-monitoring-and-pooling/cmap-node-specs/pool-checkin-stats.json
  test/integration/connection-monitoring-and-pooling/cmap-node-specs/pool-checkout-stats.json
  test/integration/connection-monitoring-and-pooling/cmap-node-specs/pool-minPoolSize-population-stats.json
  test/integration/connection-monitoring-and-pooling/cmap-node-specs/pool-minPoolSize-replace-removed-connections.json
  test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.spec.test.ts
  test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.prose.test.ts
  test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.spec.test.ts
  test/integration/unified-test-format/unified_test_format.spec.test.ts
  test/tools/cmap_spec_runner.ts
  test/tools/spec-runner/index.js
  test/tools/unified-spec-runner/entities.ts
  test/tools/unified-spec-runner/match.ts
  test/tools/unified-spec-runner/schema.ts
  test/unit/cmap/connection_pool.test.js
  test/unit/error.test.ts
Labels: Team Review

#3389 test(NODE-4590): add parallel driver benchmarks
  test/benchmarks/driverBench/common.js
  test/benchmarks/driverBench/index.js
  test/benchmarks/mongoBench/suites/bsonBench.js
  test/benchmarks/mongoBench/suites/index.js
  test/benchmarks/mongoBench/suites/multiBench.js
  test/benchmarks/mongoBench/suites/parallelBench.js
  test/benchmarks/mongoBench/suites/singleBench.js
Labels: Team Review

#3397 fix(NODE-3986): unskip MONGODB-AWS test
  src/connection_string.ts
  test/unit/assorted/auth.spec.test.ts
Labels: tracked-in-jira, Primary Review

#3396 feat(NODE-4607): add exports needed by legacy client
  src/bulk/ordered.ts
  src/bulk/unordered.ts
  src/gridfs/download.ts
  src/gridfs/upload.ts
  src/index.ts
  test/tools/utils.ts
  test/unit/index.test.ts
Labels: Team Review

#3402 test(NODE-4605, NODE-4597, NODE-4618): sync latest change stream unified tests
  test/spec/change-streams/unified/change-streams-clusterTime.json
  test/spec/change-streams/unified/change-streams-clusterTime.yml
  test/spec/change-streams/unified/change-streams-disambiguatedPaths.json
  test/spec/change-streams/unified/change-streams-disambiguatedPaths.yml
  test/spec/change-streams/unified/change-streams-showExpandedEvents.json
  test/spec/change-streams/unified/change-streams-showExpandedEvents.yml
Labels: Team Review

#3403 feat(NODE-4519): deprecate promiseLibrary and check for emitted warning
  src/index.ts
  src/mongo_client.ts
  src/promise_provider.ts
  test/integration/node-specific/custom_promise_library.test.js
  test/types/mongodb.test-d.ts
Labels: Team Review

#3388 feat(NODE-4547): mark all callback APIs as deprecated
  src/admin.ts
  src/bulk/common.ts
  src/change_stream.ts
  src/collection.ts
  src/cursor/abstract_cursor.ts
  src/cursor/aggregation_cursor.ts
  src/cursor/find_cursor.ts
  src/db.ts
  src/gridfs/index.ts
  src/gridfs/upload.ts
  src/mongo_client.ts
  src/sessions.ts
  src/utils.ts
Labels: Team Review

#3407 fix(NODE-3144): pool clear event ordering and retryability tests
  src/cmap/connection_pool.ts
  src/cmap/errors.ts
  test/integration/retryable-reads/retryable_reads.spec.prose.test.ts
  test/integration/retryable-writes/retryable_writes.spec.prose.test.ts
Labels: Team Review

#3412 fix(NODE-4639): allow PromiseProvider to be null
  src/bulk/common.ts
  src/connection_string.ts
  src/mongo_client.ts
  src/promise_provider.ts
  src/sessions.ts
  src/utils.ts
  test/integration/node-specific/cursor_async_iterator.test.js
  test/integration/node-specific/custom_promise_library.test.js
  test/types/community/client.test-d.ts
  test/unit/mongo_client.test.js
Labels: Team Review

#3408 feat(NODE-4634): add support for bulk FindOperators.hint()
  src/bulk/common.ts
  src/operations/update.ts
  test/integration/crud/bulk.test.ts
Labels: Team Review

#3399 refactor(NODE-4617): use promise apis in benchmarks
  test/benchmarks/mongoBench/benchmark.js
  test/benchmarks/mongoBench/runner.js
  test/benchmarks/mongoBench/suites/bsonBench.js
  test/benchmarks/mongoBench/suites/multiBench.js
  test/benchmarks/mongoBench/suites/singleBench.js
Labels: Team Review

#3411 refactor(NODE-4637): clean up async interval
  src/index.ts
  src/sdam/monitor.ts
  src/sdam/topology.ts
  src/utils.ts
  test/unit/sdam/monitor.test.js
  test/unit/sdam/monitor.test.ts
  test/unit/utils.test.ts
Labels: Team Review

#3410 fix(NODE-4621): ipv6 address handling in HostAddress
  src/cmap/connection.ts
  src/sdam/server_description.ts
  src/utils.ts
  test/integration/crud/misc_cursors.test.js
  test/integration/node-specific/ipv6.test.ts
  test/tools/cluster_setup.sh
  test/tools/cmap_spec_runner.ts
  test/tools/runner/config.ts
  test/tools/uri_spec_runner.ts
  test/unit/connection_string.test.ts
  test/unit/sdam/server_description.test.ts
  test/unit/utils.test.ts
Labels: Team Review

#3418 test(NODE-4648): pull prepare shell out to script and fix reporter error handling
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/prepare-shell.sh
  .evergreen/run-orchestration.sh
  .evergreen/run-tests.sh
  .gitignore
  test/integration/node-specific/examples/transactions.test.js
  test/integration/retryable-reads/retryable_reads.spec.prose.test.ts
  test/tools/reporter/mongodb_reporter.js
Labels: Team Review

#3406 refactor(NODE-4631): change_stream, gridfs to use maybeCallback
  src/bulk/common.ts
  src/change_stream.ts
  src/gridfs/index.ts
  src/gridfs/upload.ts
  src/mongo_client.ts
  src/utils.ts
  test/integration/sessions/sessions.spec.prose.test.ts
  test/unit/utils.test.ts
Labels: Team Review

#3416 chore(NODE-4641): remove wire version checks for unsupported servers
  src/operations/aggregate.ts
  src/operations/command.ts
  src/operations/delete.ts
  src/operations/find.ts
  src/operations/find_and_modify.ts
  src/operations/update.ts
  src/sdam/server.ts
  src/utils.ts
Labels: Primary Review

#3424 fix(NODE-4649): use SDAM handling for errors from min pool size population
  src/cmap/connection_pool.ts
  src/cmap/connection_pool_events.ts
  src/cmap/errors.ts
  src/sdam/server.ts
  test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.spec.test.ts
  test/tools/cmap_spec_runner.ts
  test/unit/cmap/connection_pool.test.js
Labels: Team Review

#3421 refactor(NODE-4633): executeOperation to use maybeCallback
  .eslintrc.json
  src/bulk/common.ts
  src/collection.ts
  src/mongo_client.ts
  src/operations/command.ts
  src/operations/delete.ts
  src/operations/drop.ts
  src/operations/execute_operation.ts
  src/operations/operation.ts
  src/sdam/server.ts
  src/sdam/topology.ts
  test/integration/crud/bulk.test.ts
  test/integration/crud/maxTimeMS.test.ts
  test/integration/server-selection/operation_count.test.ts
  test/integration/sessions/sessions.spec.prose.test.ts
  test/integration/sessions/sessions.test.ts
Labels: Team Review

#3423 ci(NODE-4662): remove ubuntu in favor of rhel8
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
Labels: Team Review

#3426 feat(NODE-4650): handle handshake errors with SDAM
  src/cmap/connection_pool.ts
  src/error.ts
  src/sdam/server.ts
  test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.spec.test.ts
  test/unit/sdam/server.test.ts
Labels: Team Review

#3430 test(NODE-2988): monitors wait minHeartbeatFrequencyMS between checks
  test/integration/server-discovery-and-monitoring/server_discovery_and_monitoring.prose.test.ts
  test/tools/runner/config.ts
Labels: Primary Review

#3429 feat(NODE-3255): add minPoolSizeCheckIntervalMS option to connection pool
  src/cmap/connection_pool.ts
  test/integration/server-selection/server_selection.prose.operation_count.test.ts
  test/tools/cmap_spec_runner.ts
  test/unit/cmap/connection_pool.test.js
Labels: Team Review

#3413 refactor(NODE-4638): prevent parallel calls to `fn` in the async interval
  src/sdam/monitor.ts
  test/integration/change-streams/change_stream.test.ts
  test/integration/change-streams/change_streams.spec.test.ts
  test/integration/unified-test-format/unified_test_format.spec.test.ts
  test/unit/sdam/monitor.test.ts
Labels: Team Review
