Repository mongodb/node-mongodb-native, pull requests merged in 2022-01, with the labels that each got.

#3088 fix(NODE-3843): make `GridFSBucketWriteStream.prototype.end()` return `this` for compat with community nodejs types
  src/gridfs/upload.ts
Labels: External Submission

#3094 chore(gridfs): improve error message when overrunning file length
  src/gridfs/download.ts
Labels: Team Review

#3096 docs: update api link to point to home page instead of specific version
  README.md
Labels: Team Review

#3097 chore(NODE-3717): test reorg part a-c
  test/functional/connection.test.js
  test/integration/connection-monitoring-and-pooling/connection.test.js
  test/integration/connections-survive-step-down/connections_stepdown.test.js
  test/integration/crud/aggregation.test.js
  test/integration/crud/find_cursor_methods.test.js
  test/integration/crud/misc_cursors.test.js
  test/integration/node-specific/bson-options/bsonRegExp.test.js
  test/integration/node-specific/cursor_async_iterator.test.js
  test/integration/node-specific/cursor_stream.test.js
  test/integration/node-specific/custom_promise_library.test.js
Labels: Team Review

#3095 chore: improve test filtering to use mocha hooks
  .gitignore
  .mocharc.json
  etc/sdam_viz.js
  global.d.ts
  test/functional/unit-sdam/monitoring.test.js
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
  test/readme.md
  test/tools/deprecate_warning_test_program.js
  test/tools/docker-mongodb/Dockerfile
  test/tools/docker-mongodb/docker-entrypoint.sh
  test/tools/docker_cluster.sh
  test/tools/reporter/mongodb_reporter.js
  test/tools/run_each_test.sh
  test/tools/runner/filters/client_encryption_filter.js
  test/tools/runner/filters/mongodb_topology_filter.js
  test/tools/runner/index.js
  test/tools/runner/metadata_ui.js
  test/tools/runner/plugins/session_leak_checker.js
  test/tools/sdam_viz
  test/tools/unified-spec-runner/runner.ts
  test/tools/unified-spec-runner/schema.ts
  test/tools/unified-spec-runner/unified-utils.ts
  test/tools/utils.js
  test/tsconfig.json
Labels: Team Review

#3098 chore(NODE-3717): move tests p-z
  test/functional/multiple_db.test.js
  test/functional/promises_collection.test.js
  test/functional/promises_db.test.js
  test/functional/view.test.js
  test/integration/collection-management/promise_collection_db_management.test.js
  test/integration/collection-management/view.test.ts
  test/integration/connection-monitoring-and-pooling/multiple_db.test.js
  test/integration/crud/bulk.test.js
  test/integration/crud/find_and_modify.test.js
  test/integration/crud/insert.test.js
  test/integration/crud/promise_stats.test.js
  test/integration/crud/unicode.test.js
  test/integration/index_management.test.js
  test/integration/mongodb-handshake/promise_handshake.test.js
  test/integration/node-specific/mongo_client.test.js
  test/integration/objectid.test.js
  test/integration/server_write_command.js
Labels: Team Review

#3091 fix(NODE-3792): remove offensive language throughout the codebase
  src/bulk/common.ts
  src/change_stream.ts
  src/cmap/auth/mongo_credentials.ts
  src/cmap/command_monitoring_events.ts
  src/cmap/connect.ts
  src/cmap/connection.ts
  src/cmap/wire_protocol/compression.ts
  src/constants.ts
  src/operations/add_user.ts
  src/sdam/events.ts
  src/sdam/monitor.ts
  src/sdam/server.ts
  src/sdam/server_description.ts
  src/sdam/topology.ts
  src/sdam/topology_description.ts
  src/utils.ts
  test/functional/unit-sdam/server_selection/spec.test.js
  test/functional/unit-sdam/topology.test.js
  test/manual/socks5.test.ts
  test/unit/_MISC_optional_require.test.js
  test/unit/cmap/connection.test.js
Labels: Team Review

#3104 test(NODE-3787): sync preferring error codes over messages
  test/spec/server-discovery-and-monitoring/errors/prefer-error-code.json
  test/spec/server-discovery-and-monitoring/errors/prefer-error-code.yml
Labels: Team Review

#3102 fix(NODE-3852,NODE-3854,NODE-3856): Misc typescript fixes for 4.3.1
  src/collection.ts
  src/mongo_types.ts
  test/types/community/collection/findX-recursive-types.test-d.ts
  test/types/community/collection/findX.test-d.ts
Labels: Team Review

#3105 chore(NODE-3717): test reorg - the conclusion
  .mocharc.json
  global.d.ts
  package.json
  test/functional/core/error.test.js
  test/functional/core/key/keyfile.key
  test/functional/core/shared.js
  test/functional/core/tailable_cursor.test.js
  test/functional/shared.js
  test/functional/spec-runner/context.js
  test/functional/spec-runner/index.js
  test/functional/spec-runner/matcher.js
  test/functional/spec-runner/utils.js
  test/integration/auth/mongodb_aws.test.js
  test/integration/crud/misc_cursors.test.js
  test/integration/crud/pk_factory.test.js
  test/integration/node-specific/examples/readme.md
  test/integration/node-specific/topology.test.js
  test/manual/data_lake.test.js
  test/readme.md
  test/tools/reporter/mongodb_reporter.js
  test/tools/runner/chai-addons.js
  test/unit/assorted/bulk_write.test.js
  test/unit/assorted/client.test.js
  test/unit/assorted/collations.test.js
  test/unit/assorted/connection_monitoring_and_pooling.spec.test.js
  test/unit/assorted/deprecate_warning.test.js
  test/unit/assorted/imports.test.ts
  test/unit/assorted/max_staleness.spec.test.js
  test/unit/assorted/optional_require.test.js
  test/unit/assorted/polling_srv_records_for_mongos_discovery.prose.test.ts
  test/unit/assorted/scram_iterations.test.js
  test/unit/assorted/server_discovery_and_monitoring.spec.test.js
  test/unit/assorted/server_selection.spec.test.js
  test/unit/assorted/server_selection_spec_helper.js
  test/unit/assorted/sessions_client.test.js
  test/unit/assorted/sessions_collection.test.js
  test/unit/assorted/snappy.test.js
  test/unit/assorted/wire_version.test.js
  test/unit/assorted/write_concern.test.js
  test/unit/error.test.js
Labels: Team Review

#3112 chore(NODE-3719,NODE-3883): identify causal consistency spec tests
  test/integration/causal-consistency/causal_consistency.prose.test.js
  test/integration/causal-consistency/causal_consistency.test.js
Labels: Primary Review

#3092 fix(NODE-3795): unexpected No auth provider for DEFAULT defined error
  src/connection_string.ts
  test/unit/connection_string.test.ts
Labels: Team Review

#3101 test(NODE-2556): add integration testing for listDatabases' authorizedDatabases flag
  test/integration/enumerate_databases/enumerate_databases.prose.test.ts
  test/integration/enumerate_databases/enumerate_databases.test.ts
  test/integration/node-specific/.gitkeep
Labels: Team Review

#3114 refactor(NODE-3719): consolidate srv poller prose tests
  test/unit/assorted/polling_srv_records_for_mongos_discovery.prose.test.ts
  test/unit/assorted/server_discovery_and_monitoring.spec.test.js
  test/unit/sdam/srv_polling.test.js
Labels: Team Review

#3116 test(NODE-3719): fix max staleness test to assert against correct set and other clean up
  test/integration/connections-survive-step-down/connections_survive_step_down.prose.test.js
  test/unit/assorted/max_staleness.spec.test.js
  test/unit/assorted/server_selection.spec.test.js
  test/unit/assorted/server_selection_spec_helper.js
Labels: Team Review

#3117 test(NODE-3738): fix uri spec runner
  test/integration/uri-options/uri_options.spec.test.js
  test/spec/index.js
  test/spec/uri-options/tls-options.json
  test/spec/uri-options/tls-options.yml
  test/tools/uri_spec_runner.ts
  test/unit/assorted/auth.spec.test.ts
  test/unit/assorted/uri_options.spec.test.ts
  test/unit/connection_string.spec.test.ts
Labels: Team Review

#3120 chore: update dependencies
  package-lock.json
  package.json
Labels: Team Review
