Repository mongodb/node-mongodb-native, pull requests merged in 2023-03, with the labels that each got.

#3580 perf(NODE-5017): skip server selection for session support
  .evergreen/run-serverless-tests.sh
  src/cmap/connection.ts
  src/operations/execute_operation.ts
  src/sdam/topology.ts
  test/integration/sessions/sessions.prose.test.ts
  test/integration/sessions/sessions.spec.prose.test.ts
  test/integration/sessions/sessions.test.ts
  test/unit/cmap/connection.test.ts
  test/unit/sdam/topology.test.js
Labels: Team Review

#3584 test(NODE-5092): fix fle2 collection names in legacy fle2 tests
  test/spec/client-side-encryption/tests/legacy/fle2-CreateCollection.json
  test/spec/client-side-encryption/tests/legacy/fle2-CreateCollection.yml
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.json
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.yml
Labels: Primary Review

#3577 feat(NODE-5035): enable OIDC authentication
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/setup-oidc-roles.sh
  package.json
  src/cmap/auth/mongo_credentials.ts
  src/cmap/auth/mongodb_oidc.ts
  src/cmap/auth/mongodb_oidc/aws_service_workflow.ts
  src/cmap/auth/mongodb_oidc/callback_workflow.ts
  src/cmap/auth/mongodb_oidc/service_workflow.ts
  src/cmap/auth/mongodb_oidc/token_entry_cache.ts
  src/cmap/auth/mongodb_oidc/workflow.ts
  src/cmap/auth/providers.ts
  src/cmap/connect.ts
  src/cmap/connection.ts
  test/integration/auth/mongodb_oidc.test.ts
  test/manual/mongodb_oidc.prose.test.ts
  test/mongodb.ts
  test/spec/auth/legacy/connection-string.json
  test/spec/auth/legacy/connection-string.yml
  test/unit/cmap/auth/mongodb_oidc/aws_service_workflow.test.ts
  test/unit/cmap/auth/mongodb_oidc/token_entry_cache.test.ts
  test/unit/connection_string.test.ts
Labels: Team Review

#3579 test(NODE-5070): reduce fle prose 14 flakiness on sharded clusters
  test/integration/client-side-encryption/client_side_encryption.prose.14.decryption_events.test.ts
Labels: Primary Review

#3582 fix(NODE-4854): set timeout on write and reset on message
  src/cmap/connect.ts
  src/cmap/connection.ts
  src/cmap/message_stream.ts
  test/integration/connection-monitoring-and-pooling/connection.test.ts
  test/unit/cmap/connect.test.js
  test/unit/cmap/connect.test.ts
  test/unit/cmap/connection.test.ts
Labels: Team Review

#3586 test(NODE-5093): fix fle2 collection names in legacy fle2 tests
  test/spec/client-side-encryption/tests/legacy/fle2-CreateCollection.json
  test/spec/client-side-encryption/tests/legacy/fle2-CreateCollection.yml
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.json
  test/spec/client-side-encryption/tests/legacy/fle2-EncryptedFields-vs-EncryptedFieldsMap.yml
Labels: Primary Review

#3588 chore(NODE-5073): remove dead code
  src/cmap/connection.ts
  src/cmap/message_stream.ts
  src/cmap/wire_protocol/shared.ts
  src/utils.ts
Labels: Team Review

#3598 ci(NODE-5110): update curl flags
  .evergreen/install-dependencies.sh
Labels: Team Review

#3587 deps(NODE-5084): bump dev dependencies
  .evergreen/run-gcp-kms-tests.sh
  .evergreen/run-serverless-tests.sh
  .evergreen/run-tests.sh
  package-lock.json
  package.json
  src/bulk/common.ts
  src/cmap/auth/gssapi.ts
  src/cmap/auth/mongodb_oidc/callback_workflow.ts
  src/cmap/auth/mongodb_oidc/service_workflow.ts
  src/cmap/auth/providers.ts
  src/cmap/connect.ts
  src/cmap/connection_pool.ts
  src/cmap/wire_protocol/compression.ts
  src/cursor/abstract_cursor.ts
  src/cursor/change_stream_cursor.ts
  src/deps.ts
  src/error.ts
  src/mongo_client.ts
  src/mongo_logger.ts
  src/operations/find_and_modify.ts
  src/operations/set_profiling_level.ts
  src/read_concern.ts
  src/read_preference.ts
  src/sdam/common.ts
  src/transactions.ts
  test/integration/crud/aggregation.test.ts
  test/integration/gridfs/gridfs.test.ts
  test/integration/node-specific/comment_with_falsy_values.test.ts
  test/tools/unified-spec-runner/schema.ts
  test/types/community/collection/insertX.test-d.ts
  test/unit/assorted/server_discovery_and_monitoring.spec.test.ts
Labels: Team Review

#3591 ci(NODE-5090): download node to local directory
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/init-nvm.sh
  .evergreen/install-dependencies.sh
  .evergreen/run-benchmarks.sh
  .evergreen/run-bson-ext-test.sh
  .evergreen/run-custom-csfle-tests.sh
  .gitignore
Labels: Team Review

#3589 feat(NODE-5036): reauthenticate OIDC and retry
  .evergreen/setup-oidc-roles.sh
  src/cmap/auth/auth_provider.ts
  src/cmap/auth/mongo_credentials.ts
  src/cmap/auth/mongodb_oidc.ts
  src/cmap/auth/mongodb_oidc/callback_workflow.ts
  src/cmap/auth/mongodb_oidc/workflow.ts
  src/cmap/auth/providers.ts
  src/cmap/auth/scram.ts
  src/cmap/connect.ts
  src/cmap/connection.ts
  src/cmap/connection_pool.ts
  src/error.ts
  src/index.ts
  test/integration/auth/auth.spec.test.ts
  test/manual/mongodb_oidc.prose.test.ts
  test/spec/auth/unified/reauthenticate_with_retry.json
  test/spec/auth/unified/reauthenticate_with_retry.yml
  test/spec/auth/unified/reauthenticate_without_retry.json
  test/spec/auth/unified/reauthenticate_without_retry.yml
  test/unit/cmap/auth/auth_provider.test.ts
  test/unit/cmap/connection_pool.test.js
Labels: Team Review

#3578 refactor(NODE-4685): unified spec runner to support logging tests
  src/connection_string.ts
  src/mongo_logger.ts
  test/integration/command-logging-and-monitoring/command_logging_and_monitoring.spec.test.ts
  test/tools/unified-spec-runner/entities.ts
  test/tools/unified-spec-runner/match.ts
  test/tools/unified-spec-runner/operations.ts
  test/tools/unified-spec-runner/runner.ts
  test/tools/unified-spec-runner/schema.ts
  test/unit/tools/unified_spec_runner.test.ts
Labels: Team Review

#3606 chore(NODE-5128): add script to clean dts and dts.map files
  etc/clean_definition_files.cjs
  package-lock.json
  package.json
Labels: Team Review

#3607 refactor(NODE-5136): make authentication use async / await
  .eslintrc.json
  package.json
  src/cmap/auth/auth_provider.ts
  src/cmap/auth/gssapi.ts
  src/cmap/auth/mongocr.ts
  src/cmap/auth/mongodb_aws.ts
  src/cmap/auth/mongodb_oidc.ts
  src/cmap/auth/plain.ts
  src/cmap/auth/scram.ts
  src/cmap/auth/x509.ts
  src/cmap/connect.ts
  src/cmap/connection_pool.ts
  test/manual/kerberos.test.js
  test/manual/kerberos.test.ts
  test/unit/cmap/auth/gssapi.test.js
  test/unit/cmap/auth/gssapi.test.ts
  test/unit/cmap/auth/mongodb_oidc.test.ts
  test/unit/cmap/connect.test.ts
Labels: Primary Review

#3604 fix(NODE-5126): find operations fail when passed an ObjectId as filter
  src/operations/find.ts
  test/integration/crud/find.test.js
  test/integration/crud/find_and_modify.test.js
  test/integration/gridfs/gridfs.test.ts
Labels: tracked-in-jira, Team Review, External Submission

#3596 fix(NODE-5106): prevent multiple mongo client connect()s from leaking topology
  src/mongo_client.ts
  test/integration/node-specific/mongo_client.test.ts
Labels: Team Review, External Submission

#3612 test(NODE-5147): fix broken range index test
  test/integration/client-side-encryption/client_side_encryption.prose.22.range_explicit_encryption.test.ts
Labels: Primary Review

#3615 fix(NODE-3998): metadata duplication in handshake
  src/cmap/auth/auth_provider.ts
  src/cmap/connect.ts
  src/connection_string.ts
  src/index.ts
  src/mongo_client.ts
  src/utils.ts
  test/integration/connection-monitoring-and-pooling/connection.test.ts
  test/integration/node-specific/topology.test.js
  test/tools/cmap_spec_runner.ts
  test/unit/cmap/handshake/client_metadata.test.ts
  test/unit/sdam/topology.test.js
Labels: Team Review
