Repository mongodb/node-mongodb-native, pull requests merged in 2023-07, with the labels that each got.

#3747 chore(NODE-5382): backport release automation scripts
  .github/actions/setup/action.yml
  .github/scripts/highlights.mjs
  .github/scripts/pr_list.mjs
  .github/scripts/release_notes.mjs
  .github/scripts/util.mjs
Labels: Team Review

#3742 fix(NODE-5102): fix listDatabases nameOnly setting is sent as NaN
  src/operations/list_databases.ts
  test/integration/enumerate_databases.test.ts
  test/unit/operations/list_databases.test.ts
Labels: tracked-in-jira, Team Review, External Submission

#3748 chore(NODE-5382): add 4.x release workflow
  .github/workflows/release-4.x.yml
Labels: Team Review

#3726 fix(NODE-4977): load snappy lazily
  src/cmap/wire_protocol/compression.ts
  src/deps.ts
  src/error.ts
  test/action/dependency.test.ts
  test/tools/utils.ts
  test/unit/error.test.ts
Labels: Team Review

#3751 chore: update release 4x workflow name
  .github/workflows/release-4.x.yml
Labels: Primary Review

#3746 fix(NODE-5374): do not apply cursor transform in Cursor.hasNext
  src/cursor/abstract_cursor.ts
  test/integration/crud/misc_cursors.test.js
  test/integration/node-specific/abstract_cursor.test.ts
  test/integration/node-specific/cursor_stream.test.js
Labels: Team Review

#3752 feat(NODE-5274): deprecate write concern options
  src/gridfs/upload.ts
  src/operations/aggregate.ts
  src/operations/command.ts
  src/sessions.ts
  src/write_concern.ts
  test/integration/crud/find_and_modify.test.ts
  test/integration/node-specific/mongo_client.test.ts
  test/integration/uri-options/uri.test.js
  test/unit/write_concern.test.ts
Labels: Team Review

#3754 feat(NODE-5407): update bson to 5.4.0
  package-lock.json
  package.json
Labels: Team Review

#3753 ci(NODE-4615): bump flaky operation count tests threshold
  test/integration/server-selection/server_selection.prose.operation_count.test.ts
Labels: Primary Review

#3749 refactor(NODE-5360): refactor CommandOperation to use async
  src/index.ts
  src/operations/add_user.ts
  src/operations/aggregate.ts
  src/operations/command.ts
  src/operations/count.ts
  src/operations/create_collection.ts
  src/operations/delete.ts
  src/operations/distinct.ts
  src/operations/drop.ts
  src/operations/estimated_document_count.ts
  src/operations/eval.ts
  src/operations/find.ts
  src/operations/find_and_modify.ts
  src/operations/indexes.ts
  src/operations/insert.ts
  src/operations/list_collections.ts
  src/operations/list_databases.ts
  src/operations/profiling_level.ts
  src/operations/remove_user.ts
  src/operations/run_command.ts
  src/operations/set_profiling_level.ts
  src/operations/stats.ts
  src/operations/update.ts
  src/operations/validate_collection.ts
  src/sdam/server.ts
  test/unit/operations/abstract_command.test.ts
Labels: Team Review

#3761 chore(NODE-5426): move FLE code into driver
  .gitignore
  encryption/lib/autoEncrypter.js
  encryption/lib/buffer_pool.js
  encryption/lib/clientEncryption.js
  encryption/lib/common.js
  encryption/lib/cryptoCallbacks.js
  encryption/lib/errors.js
  encryption/lib/index.js
  encryption/lib/mongocryptdManager.js
  encryption/lib/providers/aws.js
  encryption/lib/providers/azure.js
  encryption/lib/providers/gcp.js
  encryption/lib/providers/index.js
  encryption/lib/providers/utils.js
  encryption/lib/stateMachine.js
  encryption/test/autoEncrypter.test.js
  encryption/test/buffer_pool.test.js
  encryption/test/clientEncryption.test.js
  encryption/test/common.test.js
  encryption/test/cryptoCallbacks.test.js
  encryption/test/data/README.md
  encryption/test/data/cmd.json
  encryption/test/data/collection-info.json
  encryption/test/data/encrypted-document-nested.json
  encryption/test/data/encrypted-document.json
  encryption/test/data/encryptedFields.json
  encryption/test/data/key-document.json
  encryption/test/data/key1-document.json
  encryption/test/data/kms-decrypt-reply.txt
  encryption/test/data/kms-encrypt-reply.txt
  encryption/test/data/mongocryptd-reply.json
  encryption/test/index.test.js
  encryption/test/mongocryptdManager.test.js
  encryption/test/providers/credentialsProvider.test.js
  encryption/test/release.test.js
  encryption/test/requirements.helper.js
  encryption/test/stateMachine.test.js
  encryption/test/tools/chai-addons.js
  encryption/test/tools/mongodb_reporter.js
  encryption/test/types/index.test-d.ts
Labels: Primary Review

#3760 feat(NODE-5415)!: bump minimum Node.js version to v16.20.1
  .evergreen/ci_matrix_constants.js
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/install-dependencies.sh
  package.json
  test/integration/node-specific/errors.test.ts
  tsconfig.json
Labels: Team Review

#3766 feat(NODE-5186)!: remove duplicate BulkWriteResult accessors
  src/bulk/common.ts
  src/operations/aggregate.ts
  src/operations/find_and_modify.ts
  src/operations/insert.ts
Labels: Team Review

#3765 chore(NODE-5433): add id-token permission to release workflow
  .github/workflows/release-4.x.yml
  .github/workflows/release.yml
Labels: Team Review

#3769 docs(NODE-5438): Improve naming in code example for documentation
  test/integration/node-specific/examples/change_streams.test.js
Labels: Team Review

#3759 chore(NODE-5284): add script to build&link libmongocrypt bindings from driver
  etc/tooling/fle.sh
Labels: Primary Review

#3771 feat(NODE-5190)!: remove deprecated keep alive options
  src/cmap/connect.ts
  src/cmap/connection.ts
  src/connection_string.ts
  src/mongo_client.ts
  test/unit/connection_string.test.ts
  test/unit/mongo_client.test.js
Labels: Team Review

#3767 refactor(NODE-5392): refactor cursor operations to use async/await
  src/operations/collections.ts
  src/operations/execute_operation.ts
  src/operations/find.ts
  src/operations/get_more.ts
  src/operations/indexes.ts
  src/operations/kill_cursors.ts
  src/operations/list_collections.ts
  src/operations/list_databases.ts
  src/operations/operation.ts
  test/integration/collection-management/collection.test.ts
  test/integration/collection-management/collection_db_management.test.ts
  test/unit/operations/get_more.test.ts
Labels: Team Review

#3773 refactor(NODE-5437): admin operations to use async syntax
  src/operations/add_user.ts
  src/operations/create_collection.ts
  src/operations/drop.ts
  src/operations/is_capped.ts
  src/operations/options_operation.ts
  src/operations/profiling_level.ts
  src/operations/remove_user.ts
  src/operations/rename.ts
  src/operations/set_profiling_level.ts
  src/operations/stats.ts
  src/operations/validate_collection.ts
Labels: Team Review

#3772 fix(NODE-5228)!: remove unneeded fields from ConnectionPoolCreatedEvent.options
  package-lock.json
  src/cmap/connection_pool_events.ts
  test/integration/connection-monitoring-and-pooling/connection_pool.test.ts
  test/types/connection_pool_events.test-d.ts
  test/unit/cmap/connection_pool_events.test.ts
Labels: Team Review

#3780 refactor(NODE-5480): search index operations to use async syntax
  src/operations/search_indexes/create.ts
  src/operations/search_indexes/drop.ts
  src/operations/search_indexes/update.ts
Labels: Team Review

#3775 fix(NODE-4936)!: remove unsupported options from db.command and admin.command
  src/admin.ts
  src/db.ts
  src/mongo_client.ts
  src/operations/operation.ts
  src/operations/rename.ts
  src/operations/run_command.ts
  src/sessions.ts
  src/utils.ts
  test/integration/run-command/run_command.test.ts
Labels: Team Review

#3779 refactor(NODE-5422): convert FLE kms providers and errors to Typescript
  .evergreen/run-azure-kms-tests.sh
  .evergreen/run-gcp-kms-tests.sh
  .evergreen/run-kerberos-tests.sh
  .evergreen/run-serverless-tests.sh
  .evergreen/run-socks5-tests.sh
  .evergreen/run-tests.sh
  .evergreen/run-unit-tests.sh
  package-lock.json
  package.json
  src/client-side-encryption/errors.ts
  src/client-side-encryption/providers/aws.js
  src/client-side-encryption/providers/aws.ts
  src/client-side-encryption/providers/azure.js
  src/client-side-encryption/providers/azure.ts
  src/client-side-encryption/providers/gcp.js
  src/client-side-encryption/providers/gcp.ts
  src/client-side-encryption/providers/index.js
  src/client-side-encryption/providers/index.ts
  src/client-side-encryption/providers/utils.ts
  src/cmap/auth/mongodb_aws.ts
  src/deps.ts
  test/integration/client-side-encryption/client_side_encryption.prose.18.azure_kms_mock_server.test.ts
  test/unit/client-side-encryption/providers/credentialsProvider.test.ts
  test/unit/client-side-encryption/requirements.helper.js
  test/unit/client-side-encryption/requirements.helper.ts
  tsconfig.json
Labels: Primary Review

#3782 feat(NODE-5409)!: allow socks to be installed optionally
  package-lock.json
  package.json
  src/client-side-encryption/stateMachine.js
  src/cmap/connect.ts
  src/deps.ts
  test/action/dependency.test.ts
Labels: Primary Review

#3783 feat(NODE-2014)!: return executor result from withSession and withTransaction
  src/mongo_client.ts
  src/sessions.ts
  test/integration/sessions/sessions.test.ts
  test/integration/transactions/transactions.test.ts
  test/tools/unified-spec-runner/operations.ts
  test/types/sessions.test-d.ts
Labels: Team Review

#3774 refactor(NODE-5458): refactoring index operations to use async syntax
  src/collection.ts
  src/operations/common_functions.ts
  src/operations/indexes.ts
  test/integration/index_management.test.js
Labels: Primary Review

#3784 feat(NODE-4961)!: remove command result from commit and abort transaction APIs
  src/sessions.ts
  test/integration/transactions/transactions.test.ts
Labels: Team Review
