Repository mongodb/node-mongodb-native, pull requests merged in 2024-02, with the labels that each got.

#3980 test(NODE-5852): Skip transaction unpin spec tests
  test/integration/transactions/transactions.spec.test.js
Labels: Primary Review

#3983 feat(NODE-5885): upgrade BSON to `^6.3.0`
  package-lock.json
  package.json
Labels: Primary Review

#3984 perf(NODE-5854): Conditional logger instantiation and precompute willLog perf fix
  src/cmap/connection.ts
  src/cmap/connection_pool.ts
  src/mongo_client.ts
  src/mongo_logger.ts
  src/sdam/monitor.ts
  src/sdam/topology.ts
  test/integration/node-specific/feature_flags.test.ts
  test/unit/mongo_client.test.js
  test/unit/mongo_logger.test.ts
Labels: Team Review

#3985 fix(NODE-5901): propagate errors to transformed stream in cursor
  src/cursor/abstract_cursor.ts
  test/integration/node-specific/abstract_cursor.test.ts
Labels: Team Review

#3974 fix(NODE-5818): Add feature flagging to server selection logging
  src/sdam/topology.ts
  test/unit/sdam/server_selection.test.ts
Labels: Team Review

#3996 test(NODE-5938): sync retryable writes spec tests
  test/spec/retryable-writes/unified/bulkWrite-serverErrors.json
  test/spec/retryable-writes/unified/bulkWrite-serverErrors.yml
  test/spec/retryable-writes/unified/insertOne-serverErrors.json
  test/spec/retryable-writes/unified/insertOne-serverErrors.yml
  test/spec/unified-test-format/valid-pass/poc-retryable-writes.json
  test/spec/unified-test-format/valid-pass/poc-retryable-writes.yml
  test/tools/unified-spec-runner/unified-utils.ts
Labels: Primary Review

#3995 docs(NODE-5933): remove find-and-modify warning about defaults
  src/operations/find_and_modify.ts
Labels: tracked-in-jira, Primary Review, External Submission

#3991 feat(NODE-5939): Implement 6.x: cache the AWS credentials provider in the MONGODB-AWS auth logic
  src/cmap/auth/auth_provider.ts
  src/cmap/auth/mongodb_aws.ts
  src/cmap/connect.ts
  src/cmap/connection.ts
  src/cmap/connection_pool.ts
  src/index.ts
  src/mongo_client.ts
  src/mongo_client_auth_providers.ts
  test/integration/auth/mongodb_aws.test.ts
  test/integration/connection-monitoring-and-pooling/connection.test.ts
  test/unit/cmap/connect.test.ts
  test/unit/cmap/connection.test.ts
  test/unit/cmap/connection_pool.test.js
  test/unit/index.test.ts
  test/unit/mongo_client.test.js
Labels: Team Review

#3997 test(NODE-5643): sync connection string spec tests
  test/spec/connection-string/invalid-uris.json
  test/spec/connection-string/invalid-uris.yml
  test/spec/connection-string/valid-options.json
  test/spec/connection-string/valid-options.yml
  test/spec/connection-string/valid-unix_socket-absolute.json
  test/spec/connection-string/valid-unix_socket-absolute.yml
  test/spec/connection-string/valid-unix_socket-relative.json
  test/spec/connection-string/valid-unix_socket-relative.yml
  test/spec/connection-string/valid-warnings.json
  test/spec/connection-string/valid-warnings.yml
  test/unit/connection_string.spec.test.ts
Labels: Team Review

#3998 test(NODE-5807): sync cmap format spec tests
  test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.spec.test.ts
  test/spec/connection-monitoring-and-pooling/cmap-format/pool-clear-interrupt-immediately.json
  test/spec/connection-monitoring-and-pooling/cmap-format/pool-clear-interrupt-immediately.yml
Labels: Team Review

#3999 refactor(NODE-5953): move promisifying of randomBytes to utils
  src/cmap/auth/mongodb_aws.ts
  src/cmap/auth/scram.ts
  src/utils.ts
Labels: Primary Review

#3986 refactor(NODE-5912): make server.command an async function
  src/cmap/connection_pool.ts
  src/operations/command.ts
  src/operations/find.ts
  src/operations/get_more.ts
  src/operations/kill_cursors.ts
  src/operations/run_command.ts
  src/operations/search_indexes/create.ts
  src/operations/search_indexes/drop.ts
  src/operations/search_indexes/update.ts
  src/sdam/server.ts
  src/sdam/topology.ts
  test/integration/crud/abstract_operation.test.ts
  test/integration/retryable-writes/non-server-retryable_writes.test.ts
  test/integration/retryable-writes/retryable_writes.spec.prose.test.ts
  test/integration/server-selection/operation_count.test.ts
  test/tools/cmap_spec_runner.ts
  test/tools/spec-runner/context.js
  test/unit/assorted/server_discovery_and_monitoring.spec.test.ts
  test/unit/cmap/connection_pool.test.js
  test/unit/error.test.ts
  test/unit/operations/find.test.ts
  test/unit/operations/get_more.test.ts
  test/unit/operations/kill_cursors.test.ts
  test/unit/sdam/server.test.ts
  test/unit/sdam/topology.test.js
Labels: Team Review

#4001 refactor(NODE-5964): clean up prepareHandshakeDocument
  src/cmap/connect.ts
  test/unit/mongo_client.test.js
Labels: Primary Review

#3994 chore(NODE-5829): update driver dependencies
  package-lock.json
  package.json
Labels: Primary Review

#4004 chore(NODE-5972): specify TS 5.0 in package.json and package-lock
  package-lock.json
  package.json
Labels: Primary Review

#4002 fix(NODE-5944): make AWS session token optional
  src/cmap/auth/mongodb_aws.ts
  test/integration/auth/mongodb_aws.test.ts
Labels: Team Review

#4000 feat(NODE-5940): cache the AWS credentials provider in the MONGODB-AWS auth logic
  src/cmap/auth/auth_provider.ts
  src/cmap/auth/mongodb_aws.ts
  src/cmap/auth/scram.ts
  src/cmap/connect.ts
  src/cmap/connection.ts
  src/cmap/connection_pool.ts
  src/index.ts
  src/mongo_client.ts
  src/mongo_client_auth_providers.ts
  src/utils.ts
  test/integration/auth/mongodb_aws.test.ts
  test/unit/cmap/connect.test.ts
  test/unit/cmap/connection.test.ts
  test/unit/cmap/connection_pool.test.js
  test/unit/index.test.ts
  test/unit/mongo_client.test.js
Labels: Team Review

#4003 test(NODE-5731): add serverless proxy testing
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
Labels: Team Review

#4007 feat(NODE-5978): upgrade BSON to ^6.4.0
  package-lock.json
  package.json
Labels: Primary Review
