Repository mongodb/node-mongodb-native, pull requests merged in 2024-11, with the labels that each got.

#4302 docs(NODE-6458): document CSOT for explicit encryption
  src/client-side-encryption/client_encryption.ts
Labels: Primary Review

#4292 docs(NODE-6456): document CSOT pt 1
  src/collection.ts
  src/cursor/abstract_cursor.ts
  src/cursor/run_command_cursor.ts
  src/db.ts
  src/error.ts
  src/gridfs/index.ts
  src/index.ts
  src/mongo_client.ts
  src/operations/indexes.ts
  src/operations/operation.ts
  src/operations/run_command.ts
  src/sessions.ts
  test/integration/client-side-operations-timeout/node_csot.test.ts
  test/unit/index.test.ts
Labels: Team Review

#4314 ci(NODE-6501): use latest node in spec benchmarks
  .evergreen/config.in.yml
  .evergreen/config.yml
  test/benchmarks/mongoBench/constants.js
  test/benchmarks/mongoBench/runner.js
Labels: Primary Review

#4315 docs(NODE-6516): add documentation for MongoOperationTimeoutError and fix internal references
  etc/notes/errors.md
  src/client-side-encryption/auto_encrypter.ts
  src/collection.ts
  src/error.ts
  src/gridfs/download.ts
  src/gridfs/upload.ts
  src/sdam/topology.ts
  src/sessions.ts
  test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts
  test/integration/client-side-operations-timeout/client_side_operations_timeout.spec.test.ts
  test/integration/client-side-operations-timeout/client_side_operations_timeout.unit.test.ts
  test/unit/operations/get_more.test.ts
Labels: Primary Review

#4270 feat(NODE-6069): OIDC k8s machine workflow
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-oidc-prose-tests.sh
  .evergreen/run-oidc-tests-k8s.sh
  package.json
  src/cmap/auth/mongo_credentials.ts
  src/cmap/auth/mongodb_oidc.ts
  src/cmap/auth/mongodb_oidc/k8s_machine_workflow.ts
  test/integration/auth/mongodb_oidc_k8s.prose.07.test.ts
  test/spec/auth/legacy/connection-string.json
  test/spec/auth/legacy/connection-string.yml
Labels: Primary Review

#4299 test(NODE-5920): do not throw if the server returns unknown saslSupportedMechs
  test/integration/mongodb-handshake/mongodb-handshake.prose.test.ts
Labels: Primary Review

#4310 chore(NODE-6498): remove dead code in Topology
  src/index.ts
  src/sdam/common.ts
  src/sdam/topology.ts
Labels: Primary Review

#4311 test(NODE-6467): update uri options spec tests
  test/spec/uri-options/compression-options.json
  test/spec/uri-options/compression-options.yml
  test/spec/uri-options/concern-options.json
  test/spec/uri-options/concern-options.yml
  test/spec/uri-options/connection-options.json
  test/spec/uri-options/connection-options.yml
  test/spec/uri-options/connection-pool-options.json
  test/spec/uri-options/connection-pool-options.yml
  test/spec/uri-options/proxy-options.json
  test/spec/uri-options/proxy-options.yml
  test/spec/uri-options/read-preference-options.json
  test/spec/uri-options/read-preference-options.yml
  test/spec/uri-options/sdam-options.json
  test/spec/uri-options/sdam-options.yml
  test/spec/uri-options/single-threaded-options.json
  test/spec/uri-options/single-threaded-options.yml
  test/spec/uri-options/srv-options.json
  test/spec/uri-options/srv-options.yml
  test/spec/uri-options/tls-options.json
  test/spec/uri-options/tls-options.yml
  test/tools/uri_spec_runner.ts
Labels: Primary Review

#4304 chore(NODE-6459): compare CSOT performance
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/run-benchmarks.sh
  test/benchmarks/driverBench/common.js
  test/benchmarks/driverBench/index.js
  test/benchmarks/mongoBench/runner.js
Labels: Team Review

#4322 chore(NODE-6502) Use a python venv wherever we use Python in driver CI
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/run-custom-csfle-tests.sh
  .evergreen/run-socks5-tests.sh
  .evergreen/run-tests.sh
  test/readme.md
Labels: Primary Review

#4319 fix(NODE-6523): deleteMany in gridfs passes timeoutMS to predicate, not options
  src/gridfs/upload.ts
  test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts
Labels: Primary Review

#4321 perf(NODE-6525): remove setPrototype and defineProperty from hot path
  src/sessions.ts
  test/benchmarks/driverBench/index.js
Labels: Team Review

#4326 test(NODE-5722): unpin on endSessions test
  test/spec/load-balancers/transactions.json
  test/spec/load-balancers/transactions.yml
Labels: Primary Review

#4303 chore(NODE-6488): specify target=es2021 for ts compilation tests
  .evergreen/run-typescript.sh
  README.md
Labels: Team Review

#4328 test(NODE-6405): stop mongo orchestration in post task
  .evergreen/config.in.yml
  .evergreen/config.yml
Labels: Primary Review

#4296 fix(NODE-6469): pool is cleared before connection checkin on error
  src/cmap/connect.ts
  src/cmap/connection_pool.ts
  test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.spec.test.ts
  test/integration/connection-monitoring-and-pooling/connection_monitoring_and_pooling.test.ts
  test/integration/connection-monitoring-and-pooling/unified-cmap-node-specs/connection-logging.json
  test/spec/connection-monitoring-and-pooling/cmap-format/pool-create-min-size-error.json
  test/spec/connection-monitoring-and-pooling/cmap-format/pool-create-min-size-error.yml
  test/spec/server-discovery-and-monitoring/unified/pool-clear-application-error.json
  test/spec/server-discovery-and-monitoring/unified/pool-clear-application-error.yml
  test/spec/server-discovery-and-monitoring/unified/pool-clear-checkout-error.json
  test/spec/server-discovery-and-monitoring/unified/pool-clear-checkout-error.yml
  test/spec/server-discovery-and-monitoring/unified/pool-clear-min-pool-size-error.json
  test/spec/server-discovery-and-monitoring/unified/pool-clear-min-pool-size-error.yml
  test/spec/server-discovery-and-monitoring/unified/pool-cleared-error.yml
Labels: Primary Review

#4329 feat(NODE-6551): update bson to 6.10.0
  package-lock.json
  package.json
  test/benchmarks/driverBench/index.js
  test/benchmarks/mongoBench/suites/parallelBench.js
Labels: Primary Review

#4327 chore(NODE-6426): update prod dependencies
  package-lock.json
  package.json
Labels: Primary Review

#4331 chore(NODE-6565): add dependabot for github actions
  .github/dependabot.yml
Labels: Primary Review

#4330 ci(NODE-6557): Add Node.js 22 to support matrix
  .evergreen/ci_matrix_constants.js
  .evergreen/config.yml
Labels: Primary Review

#4316 chore: fix runCommand bench hello size
  test/benchmarks/mongoBench/suites/singleBench.js
Labels: Blocked
