Repository mongodb/node-mongodb-native, pull requests merged in 2025-01, with the labels that each got.

#4366 ci(NODE-6641): disable Node latest tasks
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
Labels: Primary Review

#4258 fix(NODE-6407): use conversationId returned by the server instead of hardcoded integer in SASL implementation for MONGODB-AWS.
  src/cmap/auth/mongodb_aws.ts
Labels: tracked-in-jira, External Submission

#4370 chore(NODE-6664): use correct script_name and replacement substring
  test/integration/node-specific/resource_clean_up.test.ts
  test/integration/node-specific/resource_tracking_script_builder.ts
  test/tools/fixtures/heap_resource_script.in.js
Labels: Primary Review

#4363 chore(NODE-6637): remove drivers tools env setting
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/install-dependencies.sh
Labels: Primary Review

#4371 perf(NODE-6452): Optimize CommandStartedEvent and CommandSucceededEvent constructors
  src/cmap/command_monitoring_events.ts
  src/utils.ts
  test/integration/command-logging-and-monitoring/command_monitoring.test.ts
Labels: Primary Review

#4361 test(NODE-6631): Implement integration tests for improved client.close() - sockets + timers
  test/integration/node-specific/client_close.test.ts
  test/integration/node-specific/resource_tracking_script_builder.ts
  test/tools/fixtures/process_resource_script.in.js
Labels: Primary Review

#4375 feat(NODE-6451): retry SRV and TXT lookup for DNS timeout errors
  src/connection_string.ts
  src/mongo_client.ts
  test/integration/initial-dns-seedlist-discovery/dns_seedlist.test.ts
Labels: Team Review

#4377 perf(NODE-6616): shortcircuit logging ejson.stringify
  src/mongo_logger.ts
  test/unit/mongo_logger.test.ts
Labels: Team Review

#4364 feat(NODE-6258): add signal support to find and aggregate
  src/client-side-encryption/auto_encrypter.ts
  src/client-side-encryption/client_encryption.ts
  src/client-side-encryption/state_machine.ts
  src/cmap/connection.ts
  src/cmap/connection_pool.ts
  src/cmap/wire_protocol/on_data.ts
  src/collection.ts
  src/cursor/abstract_cursor.ts
  src/cursor/aggregation_cursor.ts
  src/cursor/find_cursor.ts
  src/cursor/list_collections_cursor.ts
  src/db.ts
  src/index.ts
  src/mongo_types.ts
  src/operations/execute_operation.ts
  src/operations/list_collections.ts
  src/operations/operation.ts
  src/sdam/server.ts
  src/sdam/topology.ts
  src/utils.ts
  test/integration/client-side-encryption/driver.test.ts
  test/integration/client-side-operations-timeout/client_side_operations_timeout.unit.test.ts
  test/integration/node-specific/abort_signal.test.ts
  test/tools/utils.ts
  test/unit/client-side-encryption/state_machine.test.ts
  test/unit/utils.test.ts
Labels: Team Review

#4372 feat(NODE-6633): MongoClient.close closes active cursors
  src/cursor/abstract_cursor.ts
  src/mongo_client.ts
  test/integration/crud/find_cursor_methods.test.js
  test/integration/crud/misc_cursors.test.js
  test/integration/node-specific/abort_signal.test.ts
  test/integration/node-specific/abstract_cursor.test.ts
  test/integration/node-specific/mongo_client.test.ts
Labels: Team Review

#4380 test(NODE-4955): sync unacknowledged write spec tests
  test/spec/command-logging-and-monitoring/logging/command.json
  test/spec/command-logging-and-monitoring/logging/command.yml
  test/spec/command-logging-and-monitoring/monitoring/find.json
  test/spec/command-logging-and-monitoring/monitoring/find.yml
  test/spec/command-logging-and-monitoring/monitoring/unacknowledgedBulkWrite.json
  test/spec/command-logging-and-monitoring/monitoring/unacknowledgedBulkWrite.yml
  test/spec/command-logging-and-monitoring/monitoring/writeConcernError.json
  test/spec/command-logging-and-monitoring/monitoring/writeConcernError.yml
Labels: Primary Review

#4379 fix(NODE-6340): OIDC reauth uses caches speculative auth result
  src/cmap/auth/mongodb_oidc.ts
  test/integration/auth/mongodb_oidc.prose.test.ts
Labels: Team Review

#4376 fix(NODE-5225): concurrent MongoClient.close() calls each attempt to close the client
  src/mongo_client.ts
  test/integration/node-specific/mongo_client.test.ts
  test/unit/mongo_client.test.ts
Labels: Team Review

#4385 ci(NODE-6682, NODE-6684): deployed KMS tests and serverless tests use secrets manager
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/run-deployed-azure-kms-tests.sh
  .evergreen/run-deployed-gcp-kms-tests.sh
  .evergreen/run-serverless-tests.sh
  .evergreen/setup-serverless.sh
  test/readme.md
  test/tools/runner/config.ts
Labels: Primary Review

#4387 feat(NODE-5672): support standardized logging
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-benchmarks.sh
  src/connection_string.ts
  src/index.ts
  src/mongo_client.ts
  src/mongo_logger.ts
  test/integration/command-logging-and-monitoring/command_logging_and_monitoring.prose.test.ts
  test/integration/node-specific/abort_signal.test.ts
  test/integration/node-specific/mongo_client.test.ts
  test/tools/unified-spec-runner/entities.ts
  test/unit/connection_string.test.ts
  test/unit/index.test.ts
  test/unit/mongo_client.test.ts
Labels: Team Review

#4384 ci(NODE-6686): deployed Atlas cluster tests use secrets manager
  .evergreen/config.in.yml
  .evergreen/config.yml
  test/readme.md
Labels: Primary Review

#4368 fix(NODE-6407): use conversationId returned from server in saslContinue
  src/cmap/auth/mongodb_aws.ts
  test/integration/auth/mongodb_aws.test.ts
Labels: Team Review

#4386 ci(NODE-6685): use secrets manager for FLE tests and consolidate FLE setup in CI tooling
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/prepare-crypt-shared-lib.sh
  .evergreen/run-azure-kms-tests.sh
  .evergreen/run-custom-csfle-tests.sh
  .evergreen/run-gcp-kms-tests.sh
  .evergreen/run-serverless-tests.sh
  .evergreen/run-socks5-tests.sh
  .evergreen/run-tests.sh
  .evergreen/setup-fle.sh
  .gitignore
  test/csfle-kms-providers.js
  test/integration/client-side-encryption/client_side_encryption.prose.06.corpus.test.ts
  test/integration/client-side-encryption/client_side_encryption.prose.21.automatic_data_encryption_keys.test.ts
  test/integration/client-side-encryption/client_side_encryption.prose.22.range_explicit_encryption.test.ts
  test/integration/client-side-encryption/client_side_encryption.prose.23.range_encryption_defaults.test.ts
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
  test/integration/client-side-encryption/driver.test.ts
  test/integration/client-side-operations-timeout/client_side_operations_timeout.unit.test.ts
  test/integration/node-specific/client_close.test.ts
  test/readme.md
  test/tools/runner/config.ts
  test/tools/runner/filters/client_encryption_filter.ts
  test/tools/spec-runner/index.js
  test/tools/unified-spec-runner/unified-utils.ts
Labels: Primary Review
