Repository mongodb/node-mongodb-native, pull requests merged in 2025-08, with the labels that each got.

#4580 feat(NODE-6472): findOne and find no longer keep open cursors
  src/collection.ts
  src/index.ts
  src/operations/execute_operation.ts
  src/operations/find.ts
  test/spec/crud/unified/find.json
  test/spec/crud/unified/find.yml
  test/spec/crud/unified/findOne.json
  test/spec/crud/unified/findOne.yml
Labels: Team Review

#4608 refactor(NODE-7089): make AggregateOperation subclass ModernizedOperation
  src/cmap/connection.ts
  src/cursor/aggregation_cursor.ts
  src/cursor/explainable_cursor.ts
  src/cursor/find_cursor.ts
  src/explain.ts
  src/index.ts
  src/operations/aggregate.ts
  src/operations/command.ts
  src/operations/execute_operation.ts
  src/operations/operation.ts
  src/sdam/server.ts
  test/unit/operations/aggregate.test.js
Labels: Primary Review

#4612 refactor(NODE-7085): refactor db collection management APIs to use modernized operation
  src/operations/create_collection.ts
  src/operations/drop.ts
  src/operations/list_databases.ts
  src/operations/rename.ts
  src/operations/validate_collection.ts
  test/integration/node-specific/bson-options/use_bigint_64.test.ts
  test/integration/node-specific/validate_collection.test.ts
Labels: Primary Review

#4611 refactor(NODE-7083): index operations to modernized operation
  src/operations/indexes.ts
  src/operations/search_indexes/create.ts
  src/operations/search_indexes/update.ts
Labels: Primary Review

#4618 deps(NODE-7106): pin tar-fs@2.1.3 in lockfile
  package-lock.json
Labels: tracked-in-jira, Primary Review, External Submission, dependencies

#4597 feat(NODE-7059, NODE-7008): add support for text queries for QE string fields
  global.d.ts
  package-lock.json
  package.json
  src/client-side-encryption/client_encryption.ts
  src/index.ts
  test/integration/client-side-encryption/client_side_encryption.prose.27.text_queries.test.ts
  test/spec/client-side-encryption/etc/data/encryptedFields-prefix-suffix.json
  test/spec/client-side-encryption/etc/data/encryptedFields-substring.json
  test/spec/client-side-encryption/tests/unified/QE-Text-cleanupStructuredEncryptionData.json
  test/spec/client-side-encryption/tests/unified/QE-Text-cleanupStructuredEncryptionData.yml
  test/spec/client-side-encryption/tests/unified/QE-Text-compactStructuredEncryptionData.json
  test/spec/client-side-encryption/tests/unified/QE-Text-compactStructuredEncryptionData.yml
  test/spec/client-side-encryption/tests/unified/QE-Text-prefixPreview.json
  test/spec/client-side-encryption/tests/unified/QE-Text-prefixPreview.yml
  test/spec/client-side-encryption/tests/unified/QE-Text-substringPreview.json
  test/spec/client-side-encryption/tests/unified/QE-Text-substringPreview.yml
  test/spec/client-side-encryption/tests/unified/QE-Text-suffixPreview.json
  test/spec/client-side-encryption/tests/unified/QE-Text-suffixPreview.yml
  test/spec/unified-test-format/invalid/runOnRequirement-csfle-minLibmongocryptVersion-pattern.json
  test/spec/unified-test-format/invalid/runOnRequirement-csfle-minLibmongocryptVersion-pattern.yml
  test/spec/unified-test-format/invalid/runOnRequirement-csfle-minLibmongocryptVersion-type.json
  test/spec/unified-test-format/invalid/runOnRequirement-csfle-minLibmongocryptVersion-type.yml
  test/tools/runner/filters/client_encryption_filter.ts
  test/tools/runner/filters/libmongocrypt_version_filter.ts
  test/tools/runner/hooks/configuration.ts
  test/tools/unified-spec-runner/schema.ts
  test/tools/unified-spec-runner/unified-utils.ts
Labels: Primary Review

#4623 refactor(NODE-7087): remove ModernizedOperation and ModernizedCommandOperation
  src/index.ts
  src/mongo_client.ts
  src/operations/aggregate.ts
  src/operations/client_bulk_write/client_bulk_write.ts
  src/operations/command.ts
  src/operations/count.ts
  src/operations/create_collection.ts
  src/operations/delete.ts
  src/operations/distinct.ts
  src/operations/drop.ts
  src/operations/estimated_document_count.ts
  src/operations/execute_operation.ts
  src/operations/find.ts
  src/operations/find_and_modify.ts
  src/operations/get_more.ts
  src/operations/indexes.ts
  src/operations/insert.ts
  src/operations/kill_cursors.ts
  src/operations/list_collections.ts
  src/operations/list_databases.ts
  src/operations/operation.ts
  src/operations/profiling_level.ts
  src/operations/remove_user.ts
  src/operations/rename.ts
  src/operations/run_command.ts
  src/operations/search_indexes/create.ts
  src/operations/search_indexes/drop.ts
  src/operations/search_indexes/update.ts
  src/operations/set_profiling_level.ts
  src/operations/stats.ts
  src/operations/update.ts
  src/operations/validate_collection.ts
  src/sdam/server.ts
  test/integration/crud/abstract_operation.test.ts
  test/integration/retryable-writes/non-server-retryable_writes.test.ts
  test/integration/retryable-writes/retryable_writes.spec.prose.test.ts
  test/integration/server-selection/operation_count.test.ts
  test/unit/assorted/server_discovery_and_monitoring.spec.test.ts
  test/unit/error.test.ts
  test/unit/sdam/topology.test.ts
Labels: Primary Review

#4638 chore(NODE-7123): fix flaky CSOT test
  test/integration/change-streams/change_stream.test.ts
  test/integration/client-side-encryption/driver.test.ts
  test/integration/client-side-operations-timeout/client_side_operations_timeout.prose.test.ts
  test/integration/client-side-operations-timeout/node_csot.test.ts
  test/integration/collection-management/collection.test.ts
  test/integration/connections-survive-step-down/connections_survive_step_down.prose.test.ts
  test/integration/crud/crud_api.test.ts
  test/integration/crud/explain.test.ts
  test/integration/index_management.test.ts
  test/integration/node-specific/abstract_cursor.test.ts
  test/integration/server-selection/operation_count.test.ts
  test/integration/transactions/transactions.test.ts
  test/tools/cmap_spec_runner.ts
  test/tools/utils.ts
Labels: Primary Review
