Repository mongodb/node-mongodb-native, pull requests merged in 2025-02, with the labels that each got.

#4392 chore(NODE-6701): remove all OCSP tooling
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/run-ocsp-tests.sh
  package.json
  test/manual/ocsp_support.test.js
  test/readme.md
  test/tools/runner/hooks/configuration.ts
Labels: Primary Review

#4395 test(DRIVERS-3096): remove app insights from deployed lambda tests
  test/lambda/template.yaml
Labels: Team Review

#4396 ci(NODE-6694): kerberos tests use secrets manager
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/run-kerberos-tests.sh
  .gitignore
  test/manual/kerberos.test.ts
  test/readme.md
Labels: Primary Review

#4383 fix(NODE-6690): Remove extraneous Document in replaceOne return type
  src/collection.ts
Labels: Team Review, External Submission

#4382 test(NODE-6692): check that event emitters have error listeners
  .eslintrc.json
  .mocharc.json
  src/change_stream.ts
  src/client-side-encryption/state_machine.ts
  src/cmap/connect.ts
  src/cmap/connection.ts
  src/cmap/connection_pool.ts
  src/cursor/abstract_cursor.ts
  src/gridfs/index.ts
  src/mongo_client.ts
  src/mongo_types.ts
  src/sdam/monitor.ts
  src/sdam/server.ts
  src/sdam/srv_polling.ts
  src/sdam/topology.ts
  src/sessions.ts
  test/integration/change-streams/change_stream.test.ts
  test/integration/change-streams/change_streams.prose.test.ts
  test/integration/crud/crud_api.test.ts
  test/integration/crud/misc_cursors.test.js
  test/integration/node-specific/examples/change_streams.test.js
  test/integration/sessions/sessions.test.ts
  test/mocha_mongodb.json
  test/tools/cmap_spec_runner.ts
  test/tools/reporter/mongodb_reporter.js
  test/tools/runner/ee_checker.ts
  test/tools/runner/hooks/unhandled_checker.ts
  test/tools/unified-spec-runner/entities.ts
  test/unit/sdam/srv_polling.test.ts
Labels: Primary Review

#4399 chore(NODE-6720): migrate multibench tests
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  test/benchmarks/driver_bench/readme.md
  test/benchmarks/driver_bench/src/driver.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/aggregate_a_million_documents_and_to_array.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/aggregate_a_million_tweets_and_to_array.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/find_many_and_to_array.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/grid_fs_download.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/grid_fs_upload.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/large_doc_bulk_insert.mts
Labels: Primary Review

#4397 fix(NODE-6613): Update error messages when primaries go stale
  src/error.ts
  src/sdam/topology_description.ts
  test/spec/server-discovery-and-monitoring/rs/new_primary.json
  test/spec/server-discovery-and-monitoring/rs/new_primary.yml
  test/spec/server-discovery-and-monitoring/rs/new_primary_new_electionid.json
  test/spec/server-discovery-and-monitoring/rs/new_primary_new_electionid.yml
  test/spec/server-discovery-and-monitoring/rs/new_primary_new_setversion.json
  test/spec/server-discovery-and-monitoring/rs/new_primary_new_setversion.yml
  test/spec/server-discovery-and-monitoring/rs/primary_disconnect_electionid.json
  test/spec/server-discovery-and-monitoring/rs/primary_disconnect_electionid.yml
  test/spec/server-discovery-and-monitoring/rs/primary_disconnect_setversion.json
  test/spec/server-discovery-and-monitoring/rs/primary_disconnect_setversion.yml
  test/spec/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.json
  test/spec/server-discovery-and-monitoring/rs/setversion_greaterthan_max_without_electionid.yml
  test/spec/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.json
  test/spec/server-discovery-and-monitoring/rs/setversion_without_electionid-pre-6.0.yml
  test/spec/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.json
  test/spec/server-discovery-and-monitoring/rs/use_setversion_without_electionid-pre-6.0.yml
  test/unit/assorted/server_discovery_and_monitoring.test.ts
Labels: Primary Review

#4400 ci(NODE-6681): secrets manager for AWS auth tests
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/prepare-mongodb-aws-ecs-auth.sh
  .evergreen/run-lambda-aws-tests.sh
  .evergreen/run-mongodb-aws-test.sh
  .evergreen/setup-mongodb-aws-auth-tests.sh
  test/readme.md
Labels: Primary Review

#4402 chore(NODE-6733): add a cpu benchmark
  test/benchmarks/driver_bench/src/suites/single_bench/primes.mts
Labels: Primary Review

#4403 chore(NODE-6724): report composite benchmark scores
  test/benchmarks/driver_bench/src/driver.mts
  test/benchmarks/driver_bench/src/main.mts
  test/benchmarks/driver_bench/src/runner.mts
Labels: Primary Review

#4406 ci: rename secrets manager ARN
  .evergreen/config.in.yml
  .evergreen/config.yml
Labels: Primary Review

#4407 ci(NODE-6737): LDAP tests use secrets manager
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/run-ldap-tests.sh
  package.json
  test/manual/ldap.test.js
  test/manual/ldap.test.ts
Labels: Primary Review

#4411 ci: pull in fixed prebuild version and add kerberos to dev dependencies
  .evergreen/run-kerberos-tests.sh
  package-lock.json
  package.json
  test/manual/x509_auth.test.ts
Labels: Primary Review

#4412 test(NODE-6751): skip flaky scram test
  test/integration/auth/auth.prose.test.ts
Labels: Primary Review

#4393 ci(NODE-6678): Re-enable Node latest testing
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-azure-kms-tests.sh
  .evergreen/run-gcp-kms-tests.sh
  .evergreen/run-serverless-tests.sh
  .mocharc.js
  .mocharc.json
  package.json
  test/manual/mocharc.js
  test/manual/mocharc.json
  test/mocha_lambda.js
  test/mocha_lambda.json
  test/mocha_mongodb.js
  test/mocha_mongodb.json
Labels: Primary Review

#4416 ci(NODE-6748): unskip serverless tests
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
Labels: Primary Review

#4421 fix(NODE-6763): pass WriteConcernOptions instead on WriteConcernSettings
  src/utils.ts
  test/integration/read-write-concern/write_concern.test.ts
Labels: tracked-in-jira, Team Review, External Submission

#4417 ci(NODE-6728): test FLE on Alpine linux
  .dockerignore
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/docker/Dockerfile.musl
  .evergreen/docker/alpine.sh
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-alpine-fle-tests.sh
  .evergreen/run-kerberos-tests.sh
  package-lock.json
  package.json
  test/integration/client-side-encryption/client_side_encryption.prose.12.deadlock.test.ts
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
  test/integration/node-specific/client_encryption.test.ts
  test/tools/runner/config.ts
  test/tools/runner/hooks/configuration.ts
  test/tools/utils.ts
Labels: Primary Review

#4422 test(NODE-6745): only find python when installing native
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/install-dependencies.sh
Labels: Primary Review

#4425 ci(NODE-6768): regenerate lockfile
  package-lock.json
Labels: Primary Review

#4424 ci(NODE-6570): re-enable azure oidc auth tests
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
Labels: Primary Review

#4428 fix(NODE-6777): update BSON to 6.10.3
  package-lock.json
  package.json
Labels: Primary Review

#4423 docs(NODE-6765): sync types for findOneAndUpdate
  src/collection.ts
  test/integration/crud/find_and_modify.test.ts
  test/types/community/collection/findX.test-d.ts
Labels: tracked-in-jira, Team Review, External Submission

#4419 ci(NODE-6755): add tags to benchmarks
  test/benchmarks/driver_bench/readme.md
  test/benchmarks/driver_bench/src/driver.mts
  test/benchmarks/driver_bench/src/main.mts
  test/benchmarks/driver_bench/src/runner.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/find_many_and_empty_cursor.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/grid_fs_download.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/grid_fs_upload.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/large_doc_bulk_insert.mts
  test/benchmarks/driver_bench/src/suites/multi_bench/small_doc_bulk_insert.mts
  test/benchmarks/driver_bench/src/suites/node_specific/aggregate_a_million_documents_and_to_array.mts
  test/benchmarks/driver_bench/src/suites/node_specific/aggregate_a_million_tweets_and_to_array.mts
  test/benchmarks/driver_bench/src/suites/node_specific/cpu_baseline.mts
  test/benchmarks/driver_bench/src/suites/node_specific/find_many_and_to_array.mts
  test/benchmarks/driver_bench/src/suites/node_specific/ping.mts
  test/benchmarks/driver_bench/src/suites/parallel_bench/gridfs_multi_file_download.mts
  test/benchmarks/driver_bench/src/suites/parallel_bench/gridfs_multi_file_upload.mts
  test/benchmarks/driver_bench/src/suites/parallel_bench/ldjson_multi_file_export.mts
  test/benchmarks/driver_bench/src/suites/parallel_bench/ldjson_multi_file_upload.mts
  test/benchmarks/driver_bench/src/suites/single_bench/find_one.mts
  test/benchmarks/driver_bench/src/suites/single_bench/large_doc_insert_one.mts
  test/benchmarks/driver_bench/src/suites/single_bench/run_command.mts
  test/benchmarks/driver_bench/src/suites/single_bench/small_doc_insert_one.mts
Labels: Team Review

#4426 test(NODE-6771): sync `non-lb-connection-establishment` test
  .evergreen/prepare-crypt-shared-lib.sh
  .evergreen/setup-fle.sh
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
  test/integration/client-side-encryption/driver.test.ts
  test/integration/client-side-operations-timeout/client_side_operations_timeout.unit.test.ts
  test/integration/crud/crud.prose.test.ts
  test/spec/load-balancers/non-lb-connection-establishment.json
  test/spec/load-balancers/non-lb-connection-establishment.yml
  test/tools/runner/filters/client_encryption_filter.ts
  test/tools/runner/hooks/configuration.ts
Labels: Team Review

#4430 ci(NODE-6780): use shared kms server tooling from drivers-evergreen-tools
  .evergreen/activate-kms-venv.sh
  .evergreen/config.in.yml
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
  .evergreen/run-azure-kms-mock-server.sh
  .evergreen/run-kmip-server.sh
  .evergreen/run-kms-servers.sh
  .evergreen/setup-fle.sh
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
  test/readme.md
Labels: tracked-in-jira, Primary Review

#4431 feat(NODE-6676): add support for `nsType` in change stream create events
  src/change_stream.ts
  test/spec/change-streams/unified/change-streams-nsType.json
  test/spec/change-streams/unified/change-streams-nsType.yml
Labels: Primary Review

#4434 test(NODE-6766): skip serverless tests
  .evergreen/config.yml
  .evergreen/generate_evergreen_tasks.js
Labels: Primary Review

#4437 fix(NODE-6794): revert `@aws-sdk/credential-providers` peer compatibility change
  package-lock.json
  package.json
Labels: Primary Review

#4427 feat(NODE-6773): add support for $lookup on encrypted collections
  .gitignore
  etc/bash_to_fish.mjs
  package-lock.json
  package.json
  src/client-side-encryption/auto_encrypter.ts
  src/client-side-encryption/state_machine.ts
  test/integration/client-side-encryption/client_side_encryption.prose.25.lookup.test.ts
  test/integration/client-side-encryption/client_side_encryption.prose.test.js
  test/integration/client-side-encryption/client_side_encryption.spec.test.ts
  test/integration/client-side-encryption/driver.test.ts
  test/integration/crud/crud.prose.test.ts
  test/spec/client-side-encryption/etc/data/lookup/key-doc.json
  test/spec/client-side-encryption/etc/data/lookup/schema-csfle.json
  test/spec/client-side-encryption/etc/data/lookup/schema-csfle2.json
  test/spec/client-side-encryption/etc/data/lookup/schema-qe.json
  test/spec/client-side-encryption/etc/data/lookup/schema-qe2.json
  test/tools/runner/config.ts
  test/tools/runner/filters/filter.ts
  test/tools/runner/hooks/configuration.ts
  test/tools/spec-runner/index.js
  test/unit/client-side-encryption/auto_encrypter.test.ts
  test/unit/client-side-encryption/state_machine.test.ts
Labels: Team Review
